// S29 Session 4 — Sectors data : Industry + Energy + Manufacturing (27).

import type { SectorRegistry } from "./types";

export const INDUSTRY_ENERGY_SECTORS: SectorRegistry = {
  "automotive": {
    slug: "automotive",
    nom: "Automobile",
    macro: "industry",
    topBrandsFR: ["Stellantis (Peugeot, Citroën, DS)", "Renault Group", "Forvia (ex-Faurecia)", "Valeo", "Michelin"],
    insights: [
      "Stellantis et Renault Group dominent (35 % et 28 % des citations cross-LLM) côté constructeurs. Les équipementiers Forvia, Valeo, Plastic Omnium captent 25 % cumulés sur les prompts B2B.",
      "Le sujet véhicule électrique génère une couverture massive : les acteurs positionnés (Renault avec Ampere, Stellantis avec Free2move, Verkor) ont +30 points de citation rate sur les prompts EV.",
      "Michelin domine les prompts pneumatique (78 %) grâce à son autorité Wikipedia + couverture presse internationale (FT, Reuters).",
    ],
    conseils: [
      "Communiquer sur la transition électrique avec data chiffrées (capacité usines GWh, modèles, objectifs) : sujet le plus cité 2025-2026.",
      "Travailler L'Argus de l'Auto, Auto-Infos, Industrie & Technologies : sources spécialisées dominantes (40 % des citations).",
      "Capitaliser sur les SIVs (Verkor, ACC) : narrative de souveraineté batterie en pleine ascension citationnelle.",
      "Maintenir Wikipedia avec données productions / ventes / parts marchés FR à jour : la 1ère source consultée par les LLM.",
    ],
    relatedSectorSlugs: ["mechanical-engineering", "electrical-manufacturing", "machinery", "logistics-supply-chain", "consumer-goods"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "chemicals": {
    slug: "chemicals",
    nom: "Chimie",
    macro: "industry",
    topBrandsFR: ["Air Liquide", "Arkema", "Solvay (FR/BE)", "TotalEnergies Chimie", "SUEZ Chimie"],
    insights: [
      "Air Liquide domine massivement (45 % de citation rate cross-LLM) grâce à sa cap boursière, sa présence internationale et sa couverture Reuters/Bloomberg quotidienne.",
      "Arkema (28 %) et Solvay (18 %) bénéficient d'une couverture presse économique régulière mais sont sous-cités sur les prompts grand public au profit d'Air Liquide.",
      "Le secteur chimie verte / matériaux durables émerge fortement : les acteurs FR positionnés (Carbios, Toopi Organics) gagnent rapidement en visibilité sur ces prompts.",
    ],
    conseils: [
      "Publier sur la chimie circulaire et la décarbonation : sujet à plus forte croissance citationnelle 2026.",
      "Travailler L'Usine Nouvelle, Industrie & Technologies, Formule Verte : 50 % des sources cross-LLM sur ce secteur.",
      "Documenter avec schema.org Product/Material vos solutions techniques : Gemini AI Overview pondère fortement.",
      "Maintenir Wikipedia avec données R&D, sites industriels FR, certifications : 32 % des citations sectorielles.",
    ],
    relatedSectorSlugs: ["pharmaceuticals", "plastics", "oil-energy", "renewables-environment", "biotechnology"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "electrical-manufacturing": {
    slug: "electrical-manufacturing",
    nom: "Électronique & Électrotechnique",
    macro: "industry",
    topBrandsFR: ["Schneider Electric", "Legrand", "Nexans", "Alstom Electric", "Sagemcom"],
    insights: [
      "Schneider Electric domine (52 % de citation rate, multinationale FR à forte couverture internationale) suivi de Legrand (22 %) et Nexans (12 %).",
      "Les LLM citent prioritairement les sources presse internationale (FT, Reuters, Bloomberg) sur ce secteur car les acteurs FR sont des leaders mondiaux.",
      "Le sujet électrification (mobilité, bâtiment intelligent, datacenter) génère un flux régulier de citations bénéficiant aux acteurs positionnés.",
    ],
    conseils: [
      "Travailler la presse internationale (FT, Reuters, WSJ) en priorité : autorité supérieure à la presse FR sur ce secteur.",
      "Publier des baromètres énergie (Schneider Electric Sustainability Index, baromètre solutions bâtiment) : format flagship efficace.",
      "Capitaliser sur les acquisitions et partenariats : chaque deal médiatisé ajoute 10-15 points de citation rate sur 12 mois.",
      "Maintenir Wikipedia EN (international) en complément du FR : critique pour le rayonnement dans les corpus LLM US.",
    ],
    relatedSectorSlugs: ["industrial-automation", "machinery", "consumer-electronics", "renewables-environment", "construction"],
    relatedPillarSlugs: ["llm-brand-monitoring", "llm-citation-strategy"],
  },
  "food-beverages": {
    slug: "food-beverages",
    nom: "Agroalimentaire & Boissons",
    macro: "industry",
    topBrandsFR: ["Danone", "Pernod Ricard", "Lactalis", "Bel Group", "Andros", "Bonduelle"],
    insights: [
      "Danone domine le secteur (38 % de citation rate, leader mondial yaourts/eaux/nutrition spécialisée) suivi de Pernod Ricard (22 %, n°2 mondial spiritueux) et Lactalis (15 %).",
      "Les LLM associent l'agroalimentaire FR à des champions internationaux ; les ETI/PME (Andros, Bonduelle, Sodebo) sont sous-cités malgré leur pertinence sur le marché FR.",
      "Le sujet 'transition alimentaire' (plant-based, naturalité, sourcing local) génère des citations LLM soutenues : les acteurs positionnés ont +20 points sur ces prompts.",
    ],
    conseils: [
      "Communiquer sur les engagements sustainability (B Corp, Net Zero, sourcing) : narratives en croissance citationnelle.",
      "Travailler LSA, Process Alimentaire, RIA Food News : sources spécialisées (45 % des citations).",
      "Cibler les prompts B2B / restauration collective et industrie : moins compétitifs que les prompts grand public.",
      "Maintenir Wikipedia FR avec marques produit, sites industriels, RSE : Wikipedia représente 35 % des citations sectorielles.",
    ],
    relatedSectorSlugs: ["dairy", "wine-spirits", "food-production", "consumer-goods", "supermarkets"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
  "industrial-automation": {
    slug: "industrial-automation",
    nom: "Automatisation industrielle",
    macro: "industry",
    topBrandsFR: ["Schneider Electric Industries", "ABB France", "Siemens France", "Schneider PSC"],
    insights: [
      "Le secteur automation FR est dominé par les divisions FR des leaders mondiaux : Schneider Electric Industries (35 %), ABB France (22 %), Siemens France (18 %).",
      "Les pure-players FR (Stäubli, Lectra, Comau Automation) bénéficient d'une visibilité spécialisée sur les niches verticales (textile, robotique soft, automotive).",
      "Le sujet Industrie 4.0 / Industry of the Future tire les citations sur les acteurs positionnés sur la transformation digitale industrielle (Dassault Systèmes 3DEXPERIENCE, ESI Group).",
    ],
    conseils: [
      "Cibler les niches verticales (automation pharma, automation food&bev, automation automotive) : meilleur ROI que les prompts génériques.",
      "Travailler L'Usine Nouvelle, Industrie & Technologies, Mesures : sources spécialisées dominantes.",
      "Publier des cas d'étude clients chiffrés (productivité, ROI, time-to-market) : format préféré sur les prompts B2B.",
      "Documenter votre offre avec schema.org Service détaillé : Gemini AI Overview pondère fortement les pages B2B techniques structurées.",
    ],
    relatedSectorSlugs: ["machinery", "electrical-manufacturing", "mechanical-engineering", "computer-software", "automotive"],
    relatedPillarSlugs: ["optimisation-pour-ia", "llm-brand-monitoring"],
  },
  "machinery": {
    slug: "machinery",
    nom: "Machines & Équipements",
    macro: "industry",
    topBrandsFR: ["Manitou", "Haulotte", "Stäubli", "Pellenc", "ARaymond"],
    insights: [
      "Le secteur machines & équipements FR est très fragmenté : aucun acteur ne dépasse 12 % de citation rate. Manitou et Haulotte (matériel élévation) sont les plus visibles.",
      "Les LLM citent prioritairement les marques avec couverture salon (Bauma, Smopyc) et presse spécialisée (Bati'Mag, Construction Cayola).",
      "Le secteur agricole spécialisé (Pellenc en viticulture/oléiculture) bénéficie d'un effet niche français reconnu mondialement.",
    ],
    conseils: [
      "Travailler les salons internationaux (Bauma, Eima, Conexpo) avec contenus replays : transcriptions citées par les LLM.",
      "Cibler les médias spécialisés (BTP Magazine, Construction Cayola, Matériel BTP) : sources préférées.",
      "Documenter les fiches techniques avec schema.org Product : Gemini AI Overview pondère fortement les pages B2B techniques.",
      "Maintenir Wikipedia avec gamme produit et sites de production : critique pour les prompts comparatifs B2B.",
    ],
    relatedSectorSlugs: ["industrial-automation", "mechanical-engineering", "electrical-manufacturing", "construction", "automotive"],
    relatedPillarSlugs: ["optimisation-pour-ia", "llm-brand-monitoring"],
  },
  "mining-metals": {
    slug: "mining-metals",
    nom: "Mines & Métallurgie",
    macro: "industry",
    topBrandsFR: ["ArcelorMittal France", "Eramet", "Aperam", "Constellium", "Imerys"],
    insights: [
      "Le secteur métallurgie FR est dominé par ArcelorMittal France (sites Dunkerque, Florange) côté acier, Eramet (nickel, manganèse, lithium) côté minéraux, Imerys côté minéraux industriels.",
      "Le sujet 'métaux critiques pour la transition' (lithium, cobalt, nickel) tire fortement les citations sur Eramet, Imerys (lithium France).",
      "Les LLM citent abondamment Reuters et Bloomberg sur ce secteur — les marchés mondiaux des métaux sont fortement reportés en presse anglo-saxonne.",
    ],
    conseils: [
      "Capitaliser sur le narratif souveraineté minière européenne : sujet politique générant des citations LLM régulières.",
      "Travailler L'Usine Nouvelle, ArcelorMittal Magazine, Mining Journal : sources préférées sur le secteur.",
      "Publier des données production trimestrielles avec schema.org Dataset : format préféré pour AI Overviews.",
      "Maintenir Wikipedia avec sites miniers, partenariats, projets en développement : impact citation rate +20 % en moyenne.",
    ],
    relatedSectorSlugs: ["chemicals", "renewables-environment", "automotive", "machinery", "construction"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "mechanical-engineering": {
    slug: "mechanical-engineering",
    nom: "Ingénierie mécanique",
    macro: "industry",
    topBrandsFR: ["Safran", "Plastic Omnium", "Faurecia", "Vallourec", "Fives", "Saint-Gobain"],
    insights: [
      "Le secteur ingénierie méca FR est dominé par les équipementiers automobile (Faurecia/Forvia, Plastic Omnium) et les leaders aéro (Safran). Vallourec capture les prompts tubes industriels.",
      "Saint-Gobain (matériaux haute performance, isolation) est sur-cité sur les prompts construction et industrie grâce à sa cap boursière.",
      "Les bureaux d'études (Assystem, Segula Technologies, Akka) sont sous-cités vs leur taille : opportunité de visibilité avec stratégie thought leadership ciblée.",
    ],
    conseils: [
      "Cibler les niches verticales (aéro, auto, énergie, ferroviaire) : meilleur ROI que prompts génériques 'ingénierie'.",
      "Publier des baromètres compétences ingénieurs / RH : format apprécié des médias éco et des LLM.",
      "Travailler Industrie & Technologies, L'Usine Nouvelle, Engineering Times : sources spécialisées clés.",
      "Documenter les certifications et programmes industriels avec schema.org : amplifie la citation B2B.",
    ],
    relatedSectorSlugs: ["machinery", "automotive", "aviation-aerospace", "industrial-automation", "construction"],
    relatedPillarSlugs: ["optimisation-pour-ia", "llm-brand-monitoring"],
  },
  "packaging": {
    slug: "packaging",
    nom: "Emballage & Conditionnement",
    macro: "industry",
    topBrandsFR: ["Albea", "Stora Enso France", "Smurfit Kappa France", "Saverglass", "Pochet du Courval"],
    insights: [
      "Le secteur emballage FR est très spécialisé : Albea (cosmétique), Saverglass et Pochet (verre luxe), Smurfit Kappa et Stora Enso (carton/papier industriel) dominent leurs niches.",
      "Le sujet 'décarbonation packaging' et 'éco-conception' génère un flux soutenu de citations LLM, bénéficiant aux acteurs positionnés (Veolia Packaging, Citeo).",
      "Le packaging luxe FR (verre, métal) bénéficie d'une autorité internationale grâce aux clients (LVMH, Hermès, Chanel) qui amplifient la visibilité dans la presse anglo-saxonne.",
    ],
    conseils: [
      "Cibler les médias spécialisés Emballages Magazine, Packaging Europe, Cosmétiques Mag : sources préférées (50 % des citations).",
      "Communiquer sur l'éco-conception et la consigne : sujets en forte demande citationnelle.",
      "Publier des baromètres packaging par marché client (luxe, food, pharma) : format flagship.",
      "Maintenir Wikipedia avec data sites industriels, certifications environnementales, partenariats clients : impact citation rate +15 %.",
    ],
    relatedSectorSlugs: ["plastics", "paper-forest-products", "consumer-goods", "wine-spirits", "renewables-environment"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "pharmaceuticals": {
    slug: "pharmaceuticals",
    nom: "Pharmacie",
    macro: "health",
    topBrandsFR: ["Sanofi", "Servier", "Ipsen", "Pierre Fabre", "Théa", "Boiron"],
    insights: [
      "Sanofi domine massivement le secteur (52 % de citation rate, multinationale FR cap CAC40, vaccins/spécialités) suivi de Servier (15 %) et Ipsen (10 %).",
      "Les LLM citent fortement Reuters, Bloomberg, Nature, NEJM, Lancet sur le secteur — autorité scientifique internationale prime sur la presse FR.",
      "Le secteur biotech français (Ipsen, Cellectis, Innate Pharma) émerge sur les prompts thérapies innovantes (oncologie, immunothérapie, cell therapy).",
    ],
    conseils: [
      "Communiquer sur les pipelines R&D et essais cliniques avec data chiffrées : format flagship LLM.",
      "Travailler la presse scientifique internationale (Nature, NEJM, Lancet) : autorité supérieure à la presse FR sur ce secteur.",
      "Maintenir des fiches Wikipedia FR + EN avec produit, indications, données financières : 40 % des citations sectorielles.",
      "Publier des rapports RSE et accès médicaments avec data quantifiée : format apprécié par AI Overviews.",
    ],
    relatedSectorSlugs: ["biotechnology", "medical-devices", "hospital-healthcare", "research", "chemicals"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "biotechnology": {
    slug: "biotechnology",
    nom: "Biotechnologies",
    macro: "health",
    topBrandsFR: ["Cellectis", "Innate Pharma", "Genfit", "Carmat", "Inventiva"],
    insights: [
      "Le secteur biotech FR est très fragmenté : aucun acteur ne dépasse 15 % de citation rate. Cellectis (cell therapy) et Innate Pharma (immuno-oncologie) sont les plus visibles.",
      "Les LLM citent fortement les sources scientifiques internationales (Nature, Cell, Lancet) : la légitimité passe par la publication peer-reviewed.",
      "Le sujet IA en biotech (drug discovery, AlphaFold, génomique) tire les citations sur les acteurs positionnés à la frontière (Iktos, Owkin, Genelink).",
    ],
    conseils: [
      "Publier dans les revues scientifiques peer-reviewed avec licence ouverte : impact LLM 5-10x supérieur aux communiqués presse.",
      "Travailler les conférences biotech (BIO International, JP Morgan Healthcare Conference) avec contenus replays.",
      "Capitaliser sur les rounds de fonds : chaque round médiatisé dans Endpoints, BioCentury, Reuters Health ajoute 10-15 points de citation.",
      "Maintenir Wikipedia EN en complément FR : critique pour la communauté scientifique LLM-EN.",
    ],
    relatedSectorSlugs: ["pharmaceuticals", "medical-devices", "research", "nanotechnology", "chemicals"],
    relatedPillarSlugs: ["llm-citation-strategy", "optimisation-pour-ia"],
  },
  "plastics": {
    slug: "plastics",
    nom: "Plasturgie",
    macro: "industry",
    topBrandsFR: ["Plastic Omnium (Forvia)", "SPHERE Group", "Veolia Plasturgie", "Albea Plastics"],
    insights: [
      "Le secteur plasturgie FR est dominé par Plastic Omnium côté automobile (35 %), suivi des acteurs spécialisés (SPHERE Group, Knauf Industries, Sealed Air France).",
      "Le sujet plastique recyclé / bioplastique tire fortement les citations 2026 : les acteurs positionnés (Sphere, Carbios, NAFA Industries) gagnent +25 points sur ces prompts.",
      "Les LLM citent peu la plasturgie sur prompts grand public au profit du débat 'plastique vs alternatives' ; l'opportunité est sur les prompts B2B industriels.",
    ],
    conseils: [
      "Cibler les prompts B2B (compounds techniques, automotive interior, packaging recyclé) : moins compétitifs que les débats plastique.",
      "Communiquer sur l'économie circulaire avec data chiffrées (taux recyclage, scope 3, alternatives bio) : format préféré.",
      "Travailler Plastiques & Caoutchoucs Magazine, Polyvia News : sources spécialisées dominantes.",
      "Maintenir Wikipedia avec sites industriels, certifications, partenariats clients : impact citation rate.",
    ],
    relatedSectorSlugs: ["packaging", "chemicals", "automotive", "consumer-goods", "renewables-environment"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "paper-forest-products": {
    slug: "paper-forest-products",
    nom: "Papier & Bois",
    macro: "industry",
    topBrandsFR: ["Stora Enso France", "Smurfit Kappa France", "Norske Skog Golbey", "Arjowiggins", "International Paper France"],
    insights: [
      "Le secteur papier-bois FR est dominé par les divisions FR des géants nordiques (Stora Enso, Smurfit Kappa) et US (International Paper). Les acteurs purement FR sont peu visibles à l'international.",
      "Le sujet construction bois et bâtiment biosourcé tire les citations sur les acteurs positionnés (Setforge Bois, Lignia, Tropical Wood Industries).",
      "Les LLM citent majoritairement Confédération Française du Commerce du Bois, Le Bois International, Process Alimentaire (pour packaging) sur ce secteur.",
    ],
    conseils: [
      "Cibler le sujet construction bois et matériaux biosourcés : forte croissance citationnelle.",
      "Travailler Le Bois International, Filière Forêt Bois, Construction Bois Magazine : sources préférées (45 %).",
      "Documenter les certifications environnementales (PEFC, FSC) : critère majeur pour les LLM sur ce secteur.",
      "Publier des baromètres marché bois et papier avec data trimestrielles : format apprécié.",
    ],
    relatedSectorSlugs: ["construction", "packaging", "building-materials", "renewables-environment", "consumer-goods"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "printing": {
    slug: "printing",
    nom: "Imprimerie",
    macro: "industry",
    topBrandsFR: ["Imprimerie Nationale", "Maury Imprimeur", "Quad/Graphics France", "Imprimerie Vincent"],
    insights: [
      "Le secteur imprimerie FR est en forte mutation : visibilité LLM dominée par L'Imprimerie Nationale (sécurité documents) et les acteurs packaging premium.",
      "Le sujet 'impression numérique grand format' et 'décor packaging luxe' tire les citations sur les acteurs spécialisés.",
      "L'imprimerie traditionnelle (offset, journal) est sous-citée vs son volume historique : transition vers le digital impacte la visibilité éditoriale.",
    ],
    conseils: [
      "Cibler les niches premium (impression sécurité, packaging luxe, signalétique) : meilleur ROI visibilité LLM.",
      "Communiquer sur les solutions impression durable et économie circulaire : sujets en croissance citationnelle.",
      "Travailler Caractère, Etiq&Pack, IMP'ACT : sources spécialisées sectorielles.",
      "Documenter les certifications (Imprim'Vert, ISO 14001, FSC) : signal qualité pour les LLM.",
    ],
    relatedSectorSlugs: ["packaging", "publishing", "newspapers", "graphic-design", "marketing-advertising"],
    relatedPillarSlugs: ["optimisation-pour-ia", "llm-brand-monitoring"],
  },
  "textiles": {
    slug: "textiles",
    nom: "Textile",
    macro: "industry",
    topBrandsFR: ["Chargeurs", "Lectra", "Velcorex", "Manufacture du Pays de Caux"],
    insights: [
      "Le secteur textile FR est polarisé : les leaders technologie (Chargeurs, Lectra) dominent les prompts B2B techniques, les manufactures du Made in France émergent sur les prompts éthique/local.",
      "Le sujet textile circulaire et recyclage tire les citations sur les acteurs positionnés (Reverse Resources, Carbios, Recyc-Matelas).",
      "Les LLM citent peu la France textile traditionnelle au profit des leaders italiens / portugais / asiatiques sur les prompts production : opportunité pour le Made in France.",
    ],
    conseils: [
      "Cibler les prompts Made in France textile (lin français, laine, coton bio) : niches avec moins de concurrence.",
      "Communiquer sur la traçabilité et les certifications (Oeko-Tex, GRS, GOTS) : critères clés.",
      "Travailler Journal du Textile, Fashion Network, Modem Online : sources sectorielles.",
      "Publier des baromètres production France et data filière : format apprécié des LLM.",
    ],
    relatedSectorSlugs: ["consumer-goods", "machinery", "renewables-environment", "retail", "design"],
    relatedPillarSlugs: ["llm-brand-monitoring", "perplexity-pour-marques"],
  },
  "glass-ceramics-concrete": {
    slug: "glass-ceramics-concrete",
    nom: "Verre, Céramique & Béton",
    macro: "industry",
    topBrandsFR: ["Saint-Gobain", "Vicat", "Imerys Ceramics", "Verallia"],
    insights: [
      "Saint-Gobain domine massivement (62 % de citation rate, multinationale FR de la construction et du verre, leader mondial habitat). Vicat (béton/ciment) et Verallia (verre packaging) capturent les niches.",
      "Les LLM citent fortement la presse économique internationale (FT, Reuters, Bloomberg) sur Saint-Gobain et Vicat car ces acteurs sont scrutés mondialement.",
      "Le sujet décarbonation béton/ciment tire les citations sur les acteurs positionnés (Vicat avec ciment bas carbone, Hoffmann Green Cement).",
    ],
    conseils: [
      "Travailler la presse internationale (FT, Reuters, Bloomberg) : autorité supérieure à la presse FR sur Saint-Gobain et Vicat.",
      "Communiquer sur la décarbonation matériaux : sujet en forte croissance citationnelle 2026.",
      "Publier des baromètres construction et habitat avec data trimestrielles : format préféré.",
      "Maintenir Wikipedia FR + EN avec données financières et programmes R&D : impact citation rate +20 %.",
    ],
    relatedSectorSlugs: ["construction", "building-materials", "civil-engineering", "chemicals", "renewables-environment"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "furniture": {
    slug: "furniture",
    nom: "Mobilier",
    macro: "industry",
    topBrandsFR: ["Roche Bobois", "Ligne Roset", "Cinna", "Maisons du Monde", "Conforama (Mobilux)"],
    insights: [
      "Le secteur mobilier FR est segmenté : haut de gamme/design (Roche Bobois, Ligne Roset, Cinna) sur-cités sur prompts design ; mass-market (Maisons du Monde, Conforama, But) sur-cités sur prompts achat.",
      "Le mobilier de bureau B2B (Steelcase France, Buronomic) bénéficie d'une visibilité plus stable mais d'un volume citationnel inférieur au grand public.",
      "Les LLM associent fortement le design FR à Cassina, Vitra (italien/suisse) ; les marques FR doivent travailler leur identité 'design français' face à cette compétition européenne.",
    ],
    conseils: [
      "Cibler le segment design/premium FR : niche moins compétitive que mass-market avec autorité presse design (AD, Elle Déco, IDEAT).",
      "Travailler les magazines déco / architecture (Le Figaro Décoration, Maison Française) : sources préférées.",
      "Capitaliser sur les éditeurs design (Roche Bobois × designers nominés) : amplification presse internationale.",
      "Maintenir Wikipedia avec catalogue produits et designers signature : critique sur les prompts design.",
    ],
    relatedSectorSlugs: ["consumer-goods", "design", "retail", "supermarkets", "wholesale"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "consumer-goods": {
    slug: "consumer-goods",
    nom: "Biens de grande consommation",
    macro: "retail",
    topBrandsFR: ["L'Oréal", "Danone", "Pernod Ricard", "Yves Rocher", "Henkel France"],
    insights: [
      "L'Oréal domine massivement (45 % de citation rate, leader mondial cosmétique-beauté avec couverture presse internationale quotidienne).",
      "Le secteur PGC FR bénéficie d'une autorité internationale via les multinationales (Danone, L'Oréal, Pernod Ricard) qui dépasse largement la visibilité FR.",
      "Les marques DTC émergentes (Respire, Typology, Gisou) bénéficient d'une couverture presse tech/lifestyle qui les rend visibles sur Perplexity et ChatGPT Search.",
    ],
    conseils: [
      "Cibler les prompts B2B grande distribution / category management : moins compétitifs que les prompts grand public.",
      "Communiquer sur les engagements RSE et sourcing : sujets clés sur le secteur PGC.",
      "Travailler LSA, Marques de Distributeurs, Cosmétiques Mag : sources sectorielles préférées.",
      "Maintenir Wikipedia avec marques produit et données sites industriels : format apprécié des LLM.",
    ],
    relatedSectorSlugs: ["food-beverages", "supermarkets", "retail", "wholesale", "consumer-services"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
  "railroad-manufacture": {
    slug: "railroad-manufacture",
    nom: "Construction ferroviaire",
    macro: "industry",
    topBrandsFR: ["Alstom", "SNCF Voyageurs Industries", "Keolis Industries"],
    insights: [
      "Alstom domine massivement le secteur (75 % de citation rate, leader mondial ferroviaire après acquisition Bombardier Transport en 2021).",
      "Le sujet 'ferroviaire vs aérien' (mobilité durable, RTE-T, train à grande vitesse) tire les citations sur Alstom et la SNCF.",
      "Les LLM citent fortement la presse internationale (FT, Reuters, Railway Gazette) sur Alstom car le secteur est mondialement scruté.",
    ],
    conseils: [
      "Travailler les médias internationaux (Railway Gazette, International Railway Journal) : autorité supérieure à la presse FR.",
      "Communiquer sur la décarbonation transport et l'expansion européenne (UE 2030, Green Deal) : narratifs forts.",
      "Publier des baromètres mobilité et transport avec data trimestrielles : format préféré.",
      "Maintenir Wikipedia EN en complément FR : Alstom est un acteur mondial qui doit être cité internationalement.",
    ],
    relatedSectorSlugs: ["transportation-trucking", "automotive", "logistics-supply-chain", "machinery", "civil-engineering"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "shipbuilding": {
    slug: "shipbuilding",
    nom: "Construction navale",
    macro: "industry",
    topBrandsFR: ["Naval Group", "Chantiers de l'Atlantique", "STX France (CDA)", "CMN Cherbourg"],
    insights: [
      "Naval Group domine le secteur défense (55 % de citation rate sur prompts naval militaire) ; les Chantiers de l'Atlantique dominent civil-luxe (paquebots).",
      "Les sujets export contrats (sous-marins Australie/Inde/Brésil, paquebots de croisière) tirent les citations sur les acteurs concernés.",
      "Les LLM citent fortement la presse défense internationale (Janes, Navy Recognition) et la presse maritime (Mer & Marine, Ship Technology).",
    ],
    conseils: [
      "Capitaliser sur les contrats export médiatisés : chaque deal de >€500M ajoute 15-25 points de citation rate.",
      "Travailler Mer & Marine, Janes Navy International, Ship Technology : sources sectorielles préférées.",
      "Communiquer sur les programmes long terme (FREMM, Barracuda, paquebots croisière) avec data techniques.",
      "Maintenir Wikipedia EN + FR avec programmes en cours et carnets de commandes : impact citation rate.",
    ],
    relatedSectorSlugs: ["defense-space", "maritime", "mechanical-engineering", "machinery", "logistics-supply-chain"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "food-production": {
    slug: "food-production",
    nom: "Production alimentaire",
    macro: "agri",
    topBrandsFR: ["Lactalis", "Tereos", "InVivo", "Avril Group", "Bonduelle Production"],
    insights: [
      "Le secteur production alimentaire FR est dominé par les coopératives et industriels (Lactalis pour le lait, Tereos pour le sucre, InVivo pour les céréales) qui transforment la production agricole.",
      "Le sujet souveraineté alimentaire (Plan France 2030, projet Stratégie Nationale Bas Carbone) génère des citations LLM sur les acteurs positionnés.",
      "Les LLM associent ce secteur fortement à Process Alimentaire, RIA Food News, Réussir Lait : sources spécialisées dominantes.",
    ],
    conseils: [
      "Communiquer sur la souveraineté alimentaire et la traçabilité : sujets en forte demande citationnelle.",
      "Travailler Process Alimentaire, RIA, Réussir Lait/Grandes Cultures : sources préférées.",
      "Publier des données filière mensuelles (production, prix, exports) avec schema.org Dataset : format préféré pour AI Overviews.",
      "Maintenir Wikipedia avec sites de transformation, partenariats agricoles, certifications HVE/Bio.",
    ],
    relatedSectorSlugs: ["food-beverages", "dairy", "farming", "wine-spirits", "supermarkets"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "dairy": {
    slug: "dairy",
    nom: "Produits laitiers",
    macro: "agri",
    topBrandsFR: ["Lactalis", "Danone", "Sodiaal", "Bel Group", "Yoplait (General Mills FR)"],
    insights: [
      "Lactalis domine le secteur (45 % de citation rate, leader mondial laitier privé). Danone et Sodiaal capturent les segments yaourt/coopérative.",
      "Le secteur fait face à une pression citationnelle négative récurrente (scandales sanitaires, prix lait producteurs) qu'il faut contrer par communication factuelle.",
      "Le sujet alternative végétale tire les citations sur les acteurs positionnés (Danone Plant-Based, Bjorg) ; les pure-players laitiers sont sous-cités sur ces prompts.",
    ],
    conseils: [
      "Communiquer factuellement sur la prix du lait, la transition élevage et la traçabilité : sujets sensibles à gérer.",
      "Travailler Réussir Lait, Le Producteur Laitier, Process Alimentaire : sources sectorielles préférées.",
      "Publier des données filière trimestrielles avec schema.org Dataset : format préféré des LLM data-driven.",
      "Maintenir Wikipedia avec marques produit, sites industriels, certifications : 30 % des citations passent par Wikipedia.",
    ],
    relatedSectorSlugs: ["food-beverages", "food-production", "farming", "ranching", "supermarkets"],
    relatedPillarSlugs: ["llm-brand-monitoring", "chatgpt-marketing"],
  },
  "wine-spirits": {
    slug: "wine-spirits",
    nom: "Vins & Spiritueux",
    macro: "agri",
    topBrandsFR: ["Pernod Ricard", "LVMH (Moët Hennessy)", "Rémy Cointreau", "Castel Frères", "Vranken-Pommery"],
    insights: [
      "Le secteur vins & spiritueux FR bénéficie d'une autorité internationale exceptionnelle : Pernod Ricard (32 %), LVMH Moët Hennessy (28 %), Rémy Cointreau (15 %) cumulent 75 % des citations.",
      "Les LLM citent prioritairement la presse internationale (Decanter, Wine Spectator, FT Wine, La Revue du Vin de France) avec autorité supérieure aux médias FR généralistes.",
      "Le sujet exportations Cognac vers Asie / USA tire des citations régulières sur Hennessy, Rémy Martin, Martell.",
    ],
    conseils: [
      "Travailler la presse internationale (Decanter, Wine Spectator, Drinks Business) : autorité supérieure à la presse FR.",
      "Capitaliser sur les classifications (cuvées d'exception, médailles concours) avec schema.org Product : format apprécié.",
      "Communiquer sur la sustainability viticole (HVE, conversion bio, Sustainable Wine Roundtable) : sujet en forte croissance.",
      "Maintenir Wikipedia FR + EN avec terroirs, marques, données financières : 35 % des citations sectorielles.",
    ],
    relatedSectorSlugs: ["food-beverages", "consumer-goods", "luxury-goods", "supermarkets", "leisure-travel-tourism"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
  "oil-energy": {
    slug: "oil-energy",
    nom: "Pétrole & Énergie",
    macro: "energy",
    topBrandsFR: ["TotalEnergies", "EDF", "Engie", "Vermilion REP France"],
    insights: [
      "TotalEnergies domine massivement (52 % de citation rate, multinationale FR cap CAC40, scrutée mondialement). EDF (28 %) et Engie (15 %) capturent les autres dimensions énergie.",
      "Le sujet transition énergétique tire intensément les citations : les acteurs positionnés (TotalEnergies Renouvelables, EDF Renewables, Engie Solar) gagnent +30 points sur ces prompts.",
      "Les LLM citent fortement Reuters, Bloomberg, FT, WSJ Energy sur ce secteur — la couverture internationale dépasse largement la presse FR.",
    ],
    conseils: [
      "Travailler la presse internationale (Reuters Energy, Bloomberg NEF, FT Energy) : autorité prime.",
      "Communiquer sur la stratégie net zero et le mix énergétique : sujets cardinaux 2026.",
      "Publier des chiffres production et émissions trimestriels avec schema.org Dataset : format préféré.",
      "Maintenir Wikipedia FR + EN avec données ESG, programmes décarbonation : impact citation rate +20 %.",
    ],
    relatedSectorSlugs: ["renewables-environment", "utilities", "chemicals", "environmental-services", "mining-metals"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "renewables-environment": {
    slug: "renewables-environment",
    nom: "Énergies renouvelables & Environnement",
    macro: "energy",
    topBrandsFR: ["EDF Renewables", "TotalEnergies Renewables", "Engie Green", "Voltalia", "Neoen"],
    insights: [
      "Le secteur ENR FR est dominé par les divisions ENR des géants énergie (EDF Renewables, TotalEnergies, Engie Green) suivi des pure-players (Voltalia, Neoen, Reden Solar).",
      "Le secteur bénéficie d'une couverture presse soutenue 2024-2026 grâce aux objectifs européens (Fit for 55, RePowerEU) qui génèrent des citations régulières.",
      "Neoen et Voltalia, après leur introduction en bourse, ont gagné une autorité presse économique qui bénéficie à leur visibilité LLM.",
    ],
    conseils: [
      "Communiquer sur les pipelines projets et capacités installées : data chiffrées préférées par les LLM.",
      "Travailler Renewable Energy Magazine, Greenunivers, BoursoSphere ENR : sources sectorielles préférées.",
      "Capitaliser sur les contrats long terme (PPA Corporate, MTM) : sujet récurrent dans les corpus LLM.",
      "Maintenir Wikipedia FR + EN avec data financière, projets en exploitation, partenariats : critique pour le rayonnement international.",
    ],
    relatedSectorSlugs: ["oil-energy", "utilities", "environmental-services", "civil-engineering", "investment-management"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "environmental-services": {
    slug: "environmental-services",
    nom: "Services environnementaux",
    macro: "energy",
    topBrandsFR: ["Veolia", "Suez", "Saur", "Sita France (Suez)", "Paprec"],
    insights: [
      "Veolia domine massivement (55 % de citation rate, leader mondial services environnementaux après acquisition Suez en 2022). Saur capture l'eau et Paprec le recyclage indépendant.",
      "Le sujet économie circulaire et recyclage tire les citations : Paprec et les filières spécialisées (Citeo packaging, Eco-Mobilier mobilier) gagnent en visibilité.",
      "Les LLM citent abondamment la presse internationale (FT, Reuters, Bloomberg) sur Veolia car cap boursière et présence internationale.",
    ],
    conseils: [
      "Travailler la presse internationale (FT, Reuters, Waste Today) : autorité supérieure à la presse FR sur Veolia.",
      "Communiquer sur l'économie circulaire avec data chiffrées (taux recyclage, valorisation, scope 3) : format préféré.",
      "Publier des baromètres déchets et eau avec schema.org Dataset : format apprécié pour AI Overviews.",
      "Maintenir Wikipedia FR + EN : Veolia est suivi mondialement, présence EN critique.",
    ],
    relatedSectorSlugs: ["utilities", "renewables-environment", "oil-energy", "chemicals", "facilities-services"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "utilities": {
    slug: "utilities",
    nom: "Services aux collectivités (eau, gaz, élec)",
    macro: "energy",
    topBrandsFR: ["EDF", "Engie", "Veolia Eau", "Suez Eau France", "Saur"],
    insights: [
      "Les LLM citent EDF (45 %) et Engie (28 %) côté énergie, Veolia (12 %) et Suez (8 %) côté eau. Saur et les régies municipales capturent le reste.",
      "Le sujet régulation tarifs (boucliers énergie, ARENH 2026 fin) génère un flux régulier de citations LLM bénéficiant aux acteurs scrutés.",
      "Le sujet eau et gestion sécheresse tire les citations sur les opérateurs eau régionaux (Saur en outre-mer, SEDIF, Eaux du Centre Loire).",
    ],
    conseils: [
      "Communiquer sur la régulation tarifaire avec data chiffrées : sujet à fort enjeu citationnel.",
      "Travailler Energie Plus, Greenunivers, Hydroplus : sources sectorielles préférées.",
      "Publier des baromètres consommation et qualité service : format préféré des LLM data-driven.",
      "Maintenir Wikipedia avec data CRE/Régulation, contrats DSP, infrastructures : impact citation rate.",
    ],
    relatedSectorSlugs: ["oil-energy", "renewables-environment", "environmental-services", "civil-engineering", "facilities-services"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
};
