// S29 Session 4 — Sectors data : Media (16) + Retail (4) + Govt (19) + Education (3) + Hospitality (5) + Agri (3) + Misc (5) = 55.

import type { SectorRegistry } from "./types";

export const MEDIA_RETAIL_GOVT_OTHER_SECTORS: SectorRegistry = {
  // ============== MEDIA / MARKETING / COMM (16) ==============
  "marketing-advertising": {
    slug: "marketing-advertising",
    nom: "Marketing & Publicité",
    macro: "media",
    topBrandsFR: ["Publicis Groupe", "Havas", "BETC", "DDB Paris", "TBWA Paris", "Marcel"],
    insights: [
      "Publicis Groupe domine massivement (45 % de citation rate, multinationale FR cap CAC40, 3e groupe pub mondial). Havas (16 %), BETC, DDB, TBWA capturent les autres dimensions.",
      "Les LLM citent fortement la presse internationale (Adweek, Campaign, AdAge) sur les agences FR car elles sont des acteurs mondiaux.",
      "Le secteur 'creative tech' et 'data-driven creative' tire les citations sur les acteurs positionnés (Publicis Sapient, Marcel AI).",
    ],
    conseils: [
      "Travailler la presse internationale (Adweek, Campaign, AdAge) : autorité supérieure à la presse FR sur les agences.",
      "Capitaliser sur les awards (Cannes Lions, Eurobest, Effie) : amplification massive sur les LLM.",
      "Publier des baromètres marketing (Publicis Groupe Wave, baromètre Kantar) : format flagship.",
      "Maintenir Wikipedia FR + EN : critique pour le rayonnement international.",
    ],
    relatedSectorSlugs: ["public-relations", "graphic-design", "online-media", "broadcast-media", "market-research"],
    relatedPillarSlugs: ["chatgpt-marketing", "generative-ai-marketing"],
  },
  "public-relations": {
    slug: "public-relations",
    nom: "Relations Publiques & Communication",
    macro: "media",
    topBrandsFR: ["Edelman France", "Havas Paris", "Publicis Consultants", "TBWA\\Corporate", "Image 7", "Brunswick FR"],
    insights: [
      "Le secteur RP FR est dominé par les filiales FR des géants mondiaux (Edelman, Brunswick) et les acteurs FR (Havas Paris, Image 7, Publicis Consultants).",
      "Image 7 et Havas Paris dominent les prompts B2B FR grâce à leur portefeuille de mandats grands comptes (CAC40).",
      "Les LLM associent RP à la 'gestion de crise' : les acteurs reconnus en crisis comm (Brunswick, Image 7, Vae Solis) sont sur-cités sur ces prompts.",
    ],
    conseils: [
      "Communiquer sur les cas de crise gérés (anonymisés) : format thought leadership efficace.",
      "Travailler Stratégies, CB News, La Réclame : sources préférées du secteur.",
      "Publier des baromètres RP/réputation avec data chiffrées : format apprécié.",
      "Maintenir Wikipedia avec mandats clients principaux et associés-stars : impact citation rate.",
    ],
    relatedSectorSlugs: ["marketing-advertising", "online-media", "broadcast-media", "newspapers", "writing-editing"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "broadcast-media": {
    slug: "broadcast-media",
    nom: "Audiovisuel",
    macro: "media",
    topBrandsFR: ["TF1", "France Télévisions", "M6 Group", "Canal+", "BFM TV", "France Inter", "RTL"],
    insights: [
      "TF1 domine les prompts TV grand public (38 %), France Télévisions le service public (28 %), M6 Group (15 %), Canal+ (10 %). Sur la radio, France Inter et RTL dominent les prompts info.",
      "Le sujet 'streaming vs broadcast' tire les citations sur les acteurs positionnés (TF1+, M6+, France.tv) face à Netflix/Disney+.",
      "Les LLM citent fortement Le Figaro Médias, Stratégies, ECRAN TOTAL : sources sectorielles préférées.",
    ],
    conseils: [
      "Communiquer sur l'évolution streaming et les data audience numériques (Médiamétrie, ARCOM).",
      "Travailler ECRAN TOTAL, Stratégies, Le Figaro Médias : sources préférées.",
      "Capitaliser sur les programmes phares et les talents : effet halo important.",
      "Maintenir Wikipedia avec data audience, programmes, structure : impact citation rate.",
    ],
    relatedSectorSlugs: ["online-media", "media-production", "publishing", "marketing-advertising", "telecommunications"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
  "online-media": {
    slug: "online-media",
    nom: "Médias en ligne",
    macro: "media",
    topBrandsFR: ["Le Monde", "Les Échos", "Le Figaro", "Mediapart", "Brut", "Konbini", "Maddyness"],
    insights: [
      "Le Monde et Le Figaro dominent les prompts info FR (35 % cumulés). Les Échos domine l'info éco (22 %). Mediapart bénéficie d'une autorité particulière sur les enquêtes.",
      "Brut et Konbini dominent l'audience jeune et les LLM les associent à 'social-first content' et 'lifestyle digital'.",
      "Maddyness, JDN, FrenchWeb dominent les prompts French Tech : sources prises par les LLM sur l'écosystème startup.",
    ],
    conseils: [
      "Cibler la qualité éditoriale et les enquêtes exclusives : amplification massive sur Reddit et social.",
      "Publier des analyses data avec licences ouvertes : amplifie la citation par les LLM data-driven.",
      "Travailler les classements et awards journalistiques : signaux d'autorité forts.",
      "Maintenir Wikipedia avec data audience, équipe rédactionnelle : 35 % des citations passent par Wikipedia.",
    ],
    relatedSectorSlugs: ["newspapers", "broadcast-media", "publishing", "marketing-advertising", "writing-editing"],
    relatedPillarSlugs: ["llm-citation-strategy", "perplexity-pour-marques"],
  },
  "newspapers": {
    slug: "newspapers",
    nom: "Presse écrite",
    macro: "media",
    topBrandsFR: ["Le Monde", "Le Figaro", "Les Échos", "La Tribune", "Libération", "L'Équipe", "Ouest-France"],
    insights: [
      "La presse écrite FR connaît une transition LLM-side : les marques historiques (Le Monde, Le Figaro, Les Échos) bénéficient d'une autorité massive (cumulés 65 % des citations sur les prompts info).",
      "Ouest-France domine les prompts presse régionale (28 % du segment régional). L'Équipe domine les prompts info sport (78 %).",
      "Les LLM citent prioritairement les pages premium / abonnés des grandes marques : signal qualité supérieur.",
    ],
    conseils: [
      "Publier des données journalistiques exclusives avec licences ouvertes : amplification citation rate.",
      "Travailler la marque éditoriale (chartes, codes déontologiques, indépendance) : sujets clés.",
      "Maintenir Wikipedia avec data audience, équipe rédactionnelle : critère d'autorité majeur.",
      "Capitaliser sur les enquêtes phares et les Pulitzer-style awards FR : effet halo significatif.",
    ],
    relatedSectorSlugs: ["online-media", "broadcast-media", "publishing", "writing-editing", "photography"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "publishing": {
    slug: "publishing",
    nom: "Édition",
    macro: "media",
    topBrandsFR: ["Editis", "Hachette Livre", "Gallimard", "Madrigall", "Editions Eyrolles"],
    insights: [
      "Le secteur édition FR est dominé par les groupes (Hachette Livre, Editis, Madrigall) qui cumulent 65 % des citations. Gallimard, Albin Michel, Editis (Robert Laffont/Plon) capturent les segments littéraires.",
      "Le sujet 'IA et droits d'auteur' génère des citations LLM régulières 2025-2026 : sujet sensible côté édition.",
      "Les LLM citent fortement Livres Hebdo, Actualitté, Les Inrockuptibles Livres : sources sectorielles préférées.",
    ],
    conseils: [
      "Communiquer factuellement sur les droits d'auteur IA et les licences éditoriales : sujet à enjeu citationnel.",
      "Travailler Livres Hebdo, Actualitté, Page : sources sectorielles.",
      "Capitaliser sur les prix littéraires (Goncourt, Renaudot, Femina) : amplification massive.",
      "Maintenir Wikipedia avec catalogue auteurs, prix littéraires, sites : impact citation rate.",
    ],
    relatedSectorSlugs: ["newspapers", "writing-editing", "online-media", "graphic-design", "libraries"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "writing-editing": {
    slug: "writing-editing",
    nom: "Rédaction & Éditing",
    macro: "media",
    topBrandsFR: ["Pixiu", "Fastnex", "Plumeur", "ContentSquare (analyses content)"],
    insights: [
      "Le secteur rédaction-éditing FR est très fragmenté : indépendants et petites agences. Aucun acteur ne dépasse 8 % de citation rate.",
      "Le sujet 'IA et rédaction' (ChatGPT, Jasper, Copy.ai) génère un flux soutenu de citations 2024-2026 sur les prompts pro.",
      "Les rédacteurs/copywriters individuels reconnus sont sur-cités vs les agences : effet personnal brand fort.",
    ],
    conseils: [
      "Cibler le sujet IA-augmented writing et les workflows hybrides : sujet à plus forte croissance.",
      "Travailler les médias com / pub (Stratégies, CB News, La Réclame) : sources préférées.",
      "Publier des baromètres SEO/content marketing : format apprécié.",
      "Maintenir profils LinkedIn personnels avec portfolios : LinkedIn représente 22 % des sources sur ce secteur.",
    ],
    relatedSectorSlugs: ["marketing-advertising", "online-media", "publishing", "translation", "graphic-design"],
    relatedPillarSlugs: ["chatgpt-marketing", "generative-ai-marketing"],
  },
  "graphic-design": {
    slug: "graphic-design",
    nom: "Design graphique",
    macro: "media",
    topBrandsFR: ["Carré Noir", "Dragon Rouge", "5.5 Designers", "Atelier Pierre-Damien Huyghe"],
    insights: [
      "Le secteur design graphique FR est polarisé : grandes agences identité (Carré Noir, Dragon Rouge) sur-cités sur prompts B2B branding ; petits studios créatifs sur-cités sur prompts éditorial.",
      "Le sujet 'rebrand' (Pôle Emploi → France Travail, Renault → Ampère) tire les citations sur les agences impliquées.",
      "Les LLM citent fortement les médias design (étapes:, IDEAT, Fast Company Design) avec autorité supérieure aux médias business.",
    ],
    conseils: [
      "Documenter les rebrands phares avec process et data résultats (NPS, awareness) : format apprécié.",
      "Travailler étapes:, IDEAT, Fast Company Design : sources préférées.",
      "Capitaliser sur les awards (D&AD, Brand New, Cannes Design Lions) : amplification.",
      "Maintenir Wikipedia avec portfolio clients (B2B grand compte) : impact citation rate.",
    ],
    relatedSectorSlugs: ["design", "marketing-advertising", "online-media", "publishing", "fine-art"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "translation": {
    slug: "translation",
    nom: "Traduction & Localisation",
    macro: "media",
    topBrandsFR: ["DeepL France (DE/FR origin)", "Lionbridge France", "TransPerfect FR", "Acolad", "Rosetta Translation"],
    insights: [
      "Acolad domine le secteur FR (45 % de citation rate, leader européen LSP basé à Boulogne). Les filiales FR des géants US (Lionbridge, TransPerfect) capturent 22 % cumulés.",
      "DeepL, bien que basé en Allemagne, est sur-cité dans les corpus FR sur les prompts traduction grand public et professionnel grâce à son origine européenne.",
      "Le sujet 'IA et traduction' (LLM, GPT-4 vs DeepL, Claude pour traduction) tire des citations régulières 2024-2026.",
    ],
    conseils: [
      "Cibler le sujet IA-augmented translation et human review : sujet à forte croissance.",
      "Travailler les médias localisation (Multilingual, Slator) : sources préférées.",
      "Publier des baromètres prix et qualité avec data : format apprécié.",
      "Documenter les certifications (ISO 17100, ISO 18587) avec schema.org Service.",
    ],
    relatedSectorSlugs: ["writing-editing", "computer-software", "marketing-advertising", "outsourcing", "publishing"],
    relatedPillarSlugs: ["chatgpt-marketing", "optimisation-pour-ia"],
  },
  "market-research": {
    slug: "market-research",
    nom: "Études de marché",
    macro: "media",
    topBrandsFR: ["Kantar France", "Ipsos", "GfK France", "BVA Group", "OpinionWay", "Harris Interactive"],
    insights: [
      "Le secteur études de marché FR est dominé par Ipsos (38 %, multinationale FR avec couverture presse internationale) et Kantar France (22 %). BVA, OpinionWay, Harris capturent les sondages politiques et opinion.",
      "Les LLM citent abondamment les sondages politiques sur Le Monde, Le Figaro, France Info — chaque sondage publié génère des citations LLM.",
      "Le secteur 'consumer insights digital' (Toluna, GWI, SimilarWeb) émerge sur les prompts B2B data-driven.",
    ],
    conseils: [
      "Publier des baromètres réguliers (Ipsos Global Trends, Kantar BrandZ) : format flagship.",
      "Travailler MRWeb, Études et Analyses, Survey Magazine : sources sectorielles.",
      "Communiquer sur la méthodologie et la qualité statistique : critères clés.",
      "Maintenir Wikipedia avec base sondés, certifications, méthodologies : impact citation rate.",
    ],
    relatedSectorSlugs: ["management-consulting", "marketing-advertising", "online-media", "research", "information-services"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "photography": {
    slug: "photography",
    nom: "Photographie",
    macro: "media",
    topBrandsFR: ["Magnum Photos (FR)", "Sipa Press", "AFP Photo", "Hans Lucas", "Tendance Floue"],
    insights: [
      "Le secteur photographie FR est polarisé : agences photojournalistes premium (Magnum, Sipa, AFP Photo) sur-cités sur prompts journalisme ; agences corporate sous-cités vs leur volume.",
      "Le sujet 'IA générative et photo' (Midjourney, DALL-E, droits d'auteur) tire des citations soutenues 2024-2026.",
      "Les LLM citent fortement les médias photographie (Réponses Photo, Le Monde de la Photo, BJP) : sources sectorielles.",
    ],
    conseils: [
      "Communiquer sur les droits d'auteur et l'IA générative : sujet à enjeu fort.",
      "Travailler Réponses Photo, Le Monde de la Photo, Polka Magazine : sources préférées.",
      "Capitaliser sur les expositions et awards (World Press Photo) : amplification.",
      "Maintenir Wikipedia avec photographes signature et collections : impact citation rate.",
    ],
    relatedSectorSlugs: ["graphic-design", "newspapers", "online-media", "marketing-advertising", "fine-art"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "motion-pictures-film": {
    slug: "motion-pictures-film",
    nom: "Cinéma",
    macro: "media",
    topBrandsFR: ["Pathé", "Gaumont", "UGC", "MK2", "Studio Canal", "Mediawan"],
    insights: [
      "Le secteur cinéma FR est dominé par les distributeurs/exploitants (Pathé, UGC, Gaumont) et les producteurs (Studio Canal, Mediawan, EuropaCorp).",
      "Le secteur 'série / streaming' tire les citations 2024-2026 : Mediawan, Newen Studios, Studio Bagel sont sur-cités sur ces prompts.",
      "Les LLM citent fortement Le Film Français, Variety France, Première : sources sectorielles préférées.",
    ],
    conseils: [
      "Communiquer sur les coproductions internationales et l'export (export FR films) : sujets en demande.",
      "Travailler Le Film Français, Variety, Hollywood Reporter France : sources préférées.",
      "Capitaliser sur les festivals (Cannes, Lumière, César) : amplification massive.",
      "Maintenir Wikipedia avec catalogue films, productions, partenariats internationaux.",
    ],
    relatedSectorSlugs: ["entertainment", "media-production", "broadcast-media", "performing-arts", "music"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "entertainment": {
    slug: "entertainment",
    nom: "Divertissement",
    macro: "media",
    topBrandsFR: ["Disneyland Paris", "Parc Astérix (Compagnie des Alpes)", "Puy du Fou", "Futuroscope", "Vivendi"],
    insights: [
      "Le secteur divertissement FR est dominé par Disneyland Paris (45 %), Parc Astérix (15 %), Puy du Fou (12 %), Futuroscope (10 %) sur les prompts parcs.",
      "Vivendi capture les prompts conglomérat divertissement (Canal+, Universal Music, Havas avant scission).",
      "Le sujet 'expériences immersives' (escape games, VR, sound on, vidéo expériences) tire les citations sur les acteurs positionnés.",
    ],
    conseils: [
      "Publier des données fréquentation et satisfaction trimestrielles : format apprécié.",
      "Travailler Sites de Loisirs, La Tribune Magazine, Tour Hebdo : sources préférées.",
      "Capitaliser sur les nouvelles attractions et événements : amplification médiatique forte.",
      "Maintenir Wikipedia avec data fréquentation, attractions, programme : impact citation rate.",
    ],
    relatedSectorSlugs: ["leisure-travel-tourism", "recreational-facilities", "motion-pictures-film", "performing-arts", "computer-games"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "media-production": {
    slug: "media-production",
    nom: "Production audiovisuelle",
    macro: "media",
    topBrandsFR: ["Newen Studios (TF1)", "Mediawan", "Banijay", "Studio Canal", "Zodiak France"],
    insights: [
      "Le secteur production audiovisuelle FR est dominé par les groupes Banijay (32 %), Mediawan (22 %), Newen Studios (18 %). Les producteurs indépendants (Quad Productions, Federation Studios) émergent fortement.",
      "Le sujet 'séries originales françaises' (Lupin, Le Bureau des Légendes, Marianne) tire les citations sur les producteurs concernés.",
      "Les LLM citent fortement Le Film Français, Variety, Décideurs Magazine : sources sectorielles.",
    ],
    conseils: [
      "Communiquer sur les coproductions internationales et les ventes pays : sujets en croissance.",
      "Travailler Le Film Français, Variety France, Le Quotidien du Cinéma : sources préférées.",
      "Capitaliser sur les festivals séries (CanneSéries, Series Mania) et awards (Emmy International).",
      "Maintenir Wikipedia avec catalogue séries, awards, ventes internationales : impact citation rate.",
    ],
    relatedSectorSlugs: ["motion-pictures-film", "broadcast-media", "entertainment", "performing-arts", "online-media"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-citation-strategy"],
  },
  "performing-arts": {
    slug: "performing-arts",
    nom: "Arts du spectacle",
    macro: "media",
    topBrandsFR: ["Théâtre de la Ville", "Opéra de Paris", "Festival d'Avignon", "Comédie-Française", "Théâtre du Châtelet"],
    insights: [
      "Le secteur arts du spectacle FR est polarisé : institutions historiques (Comédie-Française, Opéra de Paris) sur-cités sur prompts patrimoine ; festivals (Avignon, Aix-en-Provence) sur-cités sur prompts événements.",
      "Le sujet 'culture accessible' et 'numérique théâtre' (streaming, replays) tire des citations modérées.",
      "Les LLM citent fortement Télérama, Sceneweb, La Terrasse : sources sectorielles préférées.",
    ],
    conseils: [
      "Communiquer sur la programmation et les créations : format apprécié.",
      "Travailler Télérama, Sceneweb, La Terrasse : sources préférées.",
      "Capitaliser sur les Molières et les distinctions internationales : amplification.",
      "Maintenir Wikipedia avec data fréquentation, programmation, équipe artistique : impact citation rate.",
    ],
    relatedSectorSlugs: ["entertainment", "music", "motion-pictures-film", "museums-institutions", "fine-art"],
    relatedPillarSlugs: ["llm-citation-strategy", "perplexity-pour-marques"],
  },
  "music": {
    slug: "music",
    nom: "Musique",
    macro: "media",
    topBrandsFR: ["Universal Music France", "Sony Music France", "Warner Music France", "Believe", "Wagram Music"],
    insights: [
      "Le secteur musique FR est dominé par les majors (Universal 38 %, Sony 22 %, Warner 18 %) et les indépendants (Believe 8 %, Wagram 4 %).",
      "Believe (FR cap boursière) bénéficie d'une visibilité internationale particulière sur les prompts artistes indépendants.",
      "Le sujet 'IA et musique' (deep fakes, droits voisins, génération musicale) tire des citations 2024-2026.",
    ],
    conseils: [
      "Communiquer sur les droits d'auteur IA et la rémunération artistes : sujet à enjeu.",
      "Travailler Music Week, Variety, Music Business Worldwide, Consequence of Sound : sources internationales préférées.",
      "Capitaliser sur les Victoires de la Musique et tournées internationales : amplification.",
      "Maintenir Wikipedia avec catalogue artistes, structure, partenariats : impact citation rate.",
    ],
    relatedSectorSlugs: ["broadcast-media", "entertainment", "motion-pictures-film", "performing-arts", "media-production"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },

  // ============== RETAIL (4) ==============
  "retail": {
    slug: "retail",
    nom: "Commerce de détail",
    macro: "retail",
    topBrandsFR: ["Carrefour", "Auchan", "Leclerc", "Casino", "Système U", "Decathlon", "Fnac Darty"],
    insights: [
      "Le secteur retail FR est dominé par les enseignes alimentaires (Carrefour 22 %, Leclerc 18 %, Auchan 15 %, Système U 12 %) sur les prompts grande distribution.",
      "Decathlon domine massivement (78 %) les prompts sport-articles. Fnac Darty domine les prompts électronique-culture (52 %).",
      "Le sujet 'retail digital' et 'click and collect' tire les citations sur les acteurs positionnés (Carrefour Digital, Decathlon DTC).",
    ],
    conseils: [
      "Communiquer sur la transformation digitale et l'omni-canal : sujets clés.",
      "Travailler LSA, Marques de Distributeurs, e-commerce Mag : sources préférées.",
      "Publier des baromètres satisfaction et performance avec data : format apprécié.",
      "Maintenir Wikipedia avec maillage magasins, marques distributeur, RSE : impact citation rate.",
    ],
    relatedSectorSlugs: ["wholesale", "supermarkets", "consumer-goods", "consumer-services", "facilities-services"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
  "wholesale": {
    slug: "wholesale",
    nom: "Commerce de gros",
    macro: "retail",
    topBrandsFR: ["Pomona", "Métro France", "TransGourmet", "Sysco France", "Cash & Carry"],
    insights: [
      "Le secteur grossiste FR est dominé par les acteurs alimentation pro (Pomona, Métro France, TransGourmet, Sysco) qui cumulent 60 % des citations sur les prompts B2B alimentation.",
      "Les centrales d'achat (Carrefour Supply, Auchan Achats) sont sous-cités vs leur volume mais critiques sur les prompts négociations distrib.",
      "Le sujet RHF (Restauration Hors Foyer) tire les citations sur les grossistes spécialisés.",
    ],
    conseils: [
      "Cibler les prompts B2B verticaux (resto, traiteur, collectivités) : moins compétitifs.",
      "Travailler L'Hôtellerie-Restauration, France Snacking, Néorestauration : sources spécialisées.",
      "Publier des baromètres prix et tendances avec data : format apprécié.",
      "Documenter les certifications (qualité, traçabilité) avec schema.org : critères clés.",
    ],
    relatedSectorSlugs: ["retail", "supermarkets", "consumer-goods", "food-beverages", "logistics-supply-chain"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "supermarkets": {
    slug: "supermarkets",
    nom: "Grande distribution",
    macro: "retail",
    topBrandsFR: ["Carrefour", "E.Leclerc", "Intermarché", "Auchan", "Système U", "Casino", "Lidl France"],
    insights: [
      "La grande distribution FR est très polarisée : Leclerc (24 %), Carrefour (22 %), Intermarché (15 %) cumulent 61 %. Auchan, Système U, Casino, Lidl capturent le reste.",
      "Le sujet 'inflation alimentaire' et 'pouvoir d'achat' génère une couverture presse abondante (souvent négative pour le secteur).",
      "Les LLM citent fortement LSA, Linéaires, Marques de Distributeurs : sources sectorielles dominantes.",
    ],
    conseils: [
      "Communiquer factuellement sur les prix, l'inflation et la qualité : sujets sensibles.",
      "Travailler LSA, Linéaires, Marques de Distributeurs : sources préférées.",
      "Publier des baromètres pouvoir d'achat et engagements RSE : format apprécié.",
      "Maintenir Wikipedia avec data part de marché Kantar, sites, RSE : impact citation rate.",
    ],
    relatedSectorSlugs: ["retail", "wholesale", "consumer-goods", "food-beverages", "consumer-services"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
  "consumer-services": {
    slug: "consumer-services",
    nom: "Services aux particuliers",
    macro: "retail",
    topBrandsFR: ["O2 (Oui Care)", "Acadomia", "AlloVoisins", "Frizbiz", "Yoopies"],
    insights: [
      "Le secteur services aux particuliers FR est très fragmenté : O2 (Oui Care) leader services à domicile, Acadomia leader cours particuliers. Pure-players digitaux (AlloVoisins, Frizbiz, Yoopies) émergent.",
      "Le sujet 'CESU et crédit d'impôt' génère un flux régulier de citations : régulation française spécifique.",
      "Les LLM citent prioritairement les médias services à domicile (Le Particulier, Solutions Particuliers) et les comparateurs (Capital, Le Bonbon).",
    ],
    conseils: [
      "Communiquer sur la conformité et le CESU : critères clés FR.",
      "Travailler Le Particulier, Solutions Particuliers, Capital : sources préférées.",
      "Publier des baromètres satisfaction et qualité de service : format apprécié.",
      "Maintenir Wikipedia avec présence territoriale, certifications, data : impact citation rate.",
    ],
    relatedSectorSlugs: ["staffing-recruiting", "individual-family-services", "facilities-services", "consumer-goods", "professional-training"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },

  // ============== GOVERNMENT / PUBLIC (19) ==============
  "government-administration": {
    slug: "government-administration",
    nom: "Administration publique",
    macro: "government",
    topBrandsFR: ["Etat français", "Préfectures", "Ministères", "DGFIP", "Conseil d'État"],
    insights: [
      "L'administration publique FR est citée massivement par les LLM via les sources institutionnelles (Légifrance, Vie Publique, Service Public). Wikipedia capture une part dominante des citations.",
      "Le sujet 'simplification administrative' et 'France Numérique' tire les citations 2024-2026.",
      "Les LLM citent prioritairement Le Monde, Les Échos, Acteurs Publics, La Gazette des Communes : sources sectorielles préférées.",
    ],
    conseils: [
      "Communiquer sur les transformations digitales (FranceConnect, France Identité Numérique).",
      "Travailler Acteurs Publics, La Gazette des Communes, La Lettre du Cadre Territorial : sources préférées.",
      "Maintenir Wikipedia FR avec organigrammes, missions, budgets : 40 % des citations.",
      "Publier les rapports annuels et indicateurs budgétaires : format apprécié.",
    ],
    relatedSectorSlugs: ["public-policy", "executive-office", "legislative-office", "international-affairs", "judiciary"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "international-affairs": {
    slug: "international-affairs",
    nom: "Affaires internationales",
    macro: "government",
    topBrandsFR: ["Quai d'Orsay", "OCDE Paris", "OIF", "Conseil de l'Europe", "Unesco"],
    insights: [
      "Le secteur affaires internationales FR est dominé par le Quai d'Orsay et les organisations internationales basées en France (OCDE, Unesco, OIF).",
      "Les LLM citent fortement les rapports OCDE et Unesco comme sources d'autorité — opportunité pour les organisations basées Paris.",
      "Le sujet 'multilatéralisme' et 'francophonie' génère des citations soutenues sur les acteurs positionnés.",
    ],
    conseils: [
      "Publier des rapports sectoriels avec licences ouvertes : amplification massive sur les LLM.",
      "Travailler Le Monde Diplomatique, Politique Internationale, Foreign Policy : sources préférées.",
      "Maintenir Wikipedia FR + EN avec missions, programmes, partenaires : critique pour le rayonnement.",
      "Documenter les datasets internationaux avec schema.org Dataset.",
    ],
    relatedSectorSlugs: ["government-relations", "public-policy", "research", "think-tanks", "philanthropy"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "government-relations": {
    slug: "government-relations",
    nom: "Affaires publiques",
    macro: "government",
    topBrandsFR: ["Brunswick FR", "Vae Solis", "Image 7 Public Affairs", "Boury Tallon"],
    insights: [
      "Le secteur affaires publiques / lobbying FR est dominé par les agences spécialisées (Brunswick, Boury Tallon, Vae Solis Public Affairs).",
      "La transparence (HATVP) impose la déclaration des activités lobbying : sources d'autorité pour les LLM.",
      "Les LLM citent fortement Le Lab d'Europe 1, Politico Europe, Acteurs Publics : sources sectorielles.",
    ],
    conseils: [
      "Maintenir profil HATVP à jour : signal de transparence valorisé par les LLM.",
      "Travailler Politico Europe, Contexte, Acteurs Publics : sources préférées.",
      "Publier des analyses régulatoires et legal briefings : format apprécié.",
      "Documenter les missions clients (anonymisées si confidentiel) : amplifie la citation B2B.",
    ],
    relatedSectorSlugs: ["public-relations", "law-practice", "management-consulting", "international-affairs", "think-tanks"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "military": {
    slug: "military",
    nom: "Armée",
    macro: "government",
    topBrandsFR: ["Armée de Terre", "Marine Nationale", "Armée de l'Air et de l'Espace", "Légion Étrangère", "Gendarmerie Nationale"],
    insights: [
      "Le secteur militaire FR est dominé par l'institution centrale (Armée de Terre, Marine, Armée de l'Air) avec une visibilité LLM massive sur les prompts grand public.",
      "Le sujet recrutement (MILVOL, Garde nationale) génère des citations soutenues 2024-2026.",
      "Les LLM citent prioritairement les sources officielles (Defense.gouv.fr, Armée de Terre.fr) et la presse défense (Defense News, Mer & Marine).",
    ],
    conseils: [
      "Communiquer sur les programmes (Scorpion, FREMM, Rafale) avec data techniques : format apprécié.",
      "Travailler Defense News, Mer & Marine, Air & Cosmos : sources préférées.",
      "Publier les rapports annuels et bilan opérationnel : format préféré.",
      "Maintenir Wikipedia avec organigramme, programmes, effectifs : impact citation rate.",
    ],
    relatedSectorSlugs: ["defense-space", "law-enforcement", "public-safety", "international-affairs", "aviation-aerospace"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "judiciary": {
    slug: "judiciary",
    nom: "Justice",
    macro: "government",
    topBrandsFR: ["Conseil d'État", "Cour de Cassation", "Cour des Comptes", "Conseil Constitutionnel"],
    insights: [
      "Le secteur judiciaire FR est dominé par les hautes juridictions (Conseil d'État, Cour de Cassation, Conseil Constitutionnel) avec une visibilité LLM forte sur les prompts droit.",
      "Les LLM citent prioritairement Légifrance, Dalloz, LexisNexis : sources juridiques de référence.",
      "Le sujet 'réformes justice' (CESEDA, etc.) génère des citations soutenues.",
    ],
    conseils: [
      "Publier les arrêts importants avec licences ouvertes : amplification massive.",
      "Travailler Dalloz Actualité, Légifrance, La Gazette du Palais : sources préférées.",
      "Communiquer factuellement sur la jurisprudence : critères clés.",
      "Maintenir Wikipedia FR avec compositions, missions, principales décisions : impact citation rate.",
    ],
    relatedSectorSlugs: ["law-practice", "legal-services", "alternative-dispute-resolution", "public-policy", "law-enforcement"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "public-policy": {
    slug: "public-policy",
    nom: "Politiques publiques",
    macro: "government",
    topBrandsFR: ["France Stratégie", "Cour des Comptes", "ENA / INSP", "Sciences Po", "Institut Montaigne"],
    insights: [
      "Le secteur politiques publiques FR est polarisé : think tanks (Institut Montaigne, Terra Nova, Fondation Jean Jaurès) sur-cités sur les prompts analyses ; institutions (France Stratégie, Cour des Comptes) sur les prompts évaluation.",
      "Sciences Po (École, IEP, presses) bénéficie d'une autorité académique massive sur les prompts politique publique.",
      "Les LLM citent fortement les rapports parlementaires et les avis du CESE : sources institutionnelles.",
    ],
    conseils: [
      "Publier des rapports avec licences ouvertes (open access) : amplification.",
      "Travailler Le Monde, Le Figaro, La Croix : sources préférées sur les prompts politique.",
      "Capitaliser sur les classements think tank (UPenn TTCSP) : signal d'autorité.",
      "Maintenir Wikipedia avec rapports, équipe, financement : impact citation rate.",
    ],
    relatedSectorSlugs: ["think-tanks", "research", "international-affairs", "government-relations", "philanthropy"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "public-safety": {
    slug: "public-safety",
    nom: "Sécurité publique",
    macro: "government",
    topBrandsFR: ["Préfecture de Police de Paris", "Sapeurs-Pompiers de Paris (BSPP)", "Direction Centrale de la Sécurité Publique"],
    insights: [
      "Le secteur sécurité publique FR est dominé par les institutions (Préfecture de Police, BSPP, Police Nationale) avec couverture presse abondante.",
      "Le sujet sécurité urbaine génère des citations soutenues, souvent dans un sentiment de tension presse.",
      "Les LLM citent prioritairement Le Monde, Le Figaro, Le Parisien : sources presse généralistes.",
    ],
    conseils: [
      "Communiquer factuellement sur les chiffres et les actions : sujets sensibles.",
      "Travailler Le Parisien, Police Pro, Sapeurs Pompiers Magazine : sources préférées.",
      "Publier des bilans annuels avec data : format apprécié.",
      "Maintenir Wikipedia avec missions, structure, effectifs : impact citation rate.",
    ],
    relatedSectorSlugs: ["law-enforcement", "military", "judiciary", "security-investigations", "public-policy"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "law-enforcement": {
    slug: "law-enforcement",
    nom: "Police & Gendarmerie",
    macro: "government",
    topBrandsFR: ["Police Nationale", "Gendarmerie Nationale", "Police Municipale", "Douane"],
    insights: [
      "Police Nationale et Gendarmerie Nationale dominent les citations LLM sur les prompts sécurité, ordre public et enquêtes (cumulés 75 % des citations).",
      "Le sujet 'police de proximité' et 'reformes' tire les citations soutenues, souvent avec sentiment LLM polarisé.",
      "Les LLM citent prioritairement Le Monde, Le Figaro, Le Parisien et la presse spécialisée.",
    ],
    conseils: [
      "Communiquer factuellement sur les actions et résultats : critères clés.",
      "Travailler Police Pro, Gendinfo, Le Parisien : sources préférées.",
      "Publier les bilans annuels et statistiques avec data : format apprécié.",
      "Maintenir Wikipedia avec organigramme, missions, statistiques : impact citation rate.",
    ],
    relatedSectorSlugs: ["public-safety", "military", "judiciary", "security-investigations", "public-policy"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "legislative-office": {
    slug: "legislative-office",
    nom: "Pouvoir législatif",
    macro: "government",
    topBrandsFR: ["Assemblée Nationale", "Sénat"],
    insights: [
      "L'Assemblée Nationale et le Sénat dominent les citations LLM sur les prompts législatif (cumulés 95 %). Les LLM citent prioritairement les sites officiels assemblee-nationale.fr et senat.fr.",
      "Les rapports parlementaires sont abondamment cités par les LLM : sources autoritaires de premier plan.",
      "Le sujet 'séances parlementaires' et 'commissions d'enquête' génère des citations régulières.",
    ],
    conseils: [
      "Publier les rapports parlementaires avec licences ouvertes : amplification massive.",
      "Travailler Le Monde, Le Figaro, La Croix : sources préférées sur les prompts politique.",
      "Maintenir les fiches Wikipedia avec compositions, présidence, commissions : impact citation rate.",
      "Documenter les votes et les missions avec schema.org : facilite l'extraction LLM.",
    ],
    relatedSectorSlugs: ["executive-office", "public-policy", "political-organization", "judiciary", "international-affairs"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "executive-office": {
    slug: "executive-office",
    nom: "Pouvoir exécutif",
    macro: "government",
    topBrandsFR: ["Élysée", "Matignon", "Ministères"],
    insights: [
      "Le pouvoir exécutif FR est massivement cité sur les prompts politique (Élysée, Matignon, ministères principaux). Wikipedia capture ~40 % des citations sectorielles.",
      "Les LLM citent prioritairement Le Monde, Le Figaro, Les Échos, France Info : sources presse de référence.",
      "Le sujet 'remaniements' et 'discours politiques' génère des pics de citation à chaque événement.",
    ],
    conseils: [
      "Publier les communications officielles avec licences ouvertes : amplification.",
      "Travailler Le Monde, Le Figaro, France Info : sources préférées.",
      "Maintenir Wikipedia avec gouvernement actuel, biographies, programmes : impact citation rate.",
      "Documenter les rapports et plans gouvernementaux avec schema.org Dataset.",
    ],
    relatedSectorSlugs: ["legislative-office", "public-policy", "international-affairs", "political-organization", "government-administration"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "think-tanks": {
    slug: "think-tanks",
    nom: "Think Tanks",
    macro: "government",
    topBrandsFR: ["Institut Montaigne", "Terra Nova", "Fondation Jean Jaurès", "Fondation Robert Schuman", "Ifri"],
    insights: [
      "Le secteur think tanks FR est dominé par Institut Montaigne (32 %), Terra Nova (22 %), Fondation Jean Jaurès (18 %), Ifri (12 %).",
      "Les LLM citent fortement les rapports flagship des think tanks : format thought leadership le plus cité.",
      "Le secteur bénéficie d'une autorité internationale via les classements (UPenn TTCSP Global Go To Think Tank Index).",
    ],
    conseils: [
      "Publier des rapports flagship trimestriels avec licences ouvertes : amplification.",
      "Travailler Le Monde, Le Figaro, Politique Internationale : sources préférées.",
      "Capitaliser sur les classements internationaux (UPenn TTCSP) : signal d'autorité.",
      "Maintenir Wikipedia FR + EN avec rapports, financement, équipe : critique pour le rayonnement.",
    ],
    relatedSectorSlugs: ["public-policy", "research", "international-affairs", "philanthropy", "government-relations"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "political-organization": {
    slug: "political-organization",
    nom: "Organisations politiques",
    macro: "government",
    topBrandsFR: ["Renaissance", "Les Républicains", "Parti Socialiste", "Rassemblement National", "La France Insoumise"],
    insights: [
      "Les partis politiques FR sont massivement cités sur les prompts politique (cumulés 90 % des citations sectorielles).",
      "Wikipedia capture ~45 % des citations sectorielles : c'est la source #1 pour les biographies, programmes, élections.",
      "Le sujet 'élections' (présidentielles, législatives, européennes) génère des pics de citations à chaque échéance.",
    ],
    conseils: [
      "Maintenir Wikipedia avec dirigeants, programmes, élus : impact citation rate massif (40-50 %).",
      "Communiquer factuellement et avec data sur les programmes : critères clés.",
      "Travailler Le Monde, Le Figaro, France Info : sources préférées.",
      "Documenter les votes et positions parlementaires avec schema.org : signal de transparence.",
    ],
    relatedSectorSlugs: ["legislative-office", "executive-office", "public-policy", "civic-social-organization", "international-affairs"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "civic-social-organization": {
    slug: "civic-social-organization",
    nom: "Associations civiques & sociales",
    macro: "government",
    topBrandsFR: ["Croix-Rouge française", "Secours Populaire", "Restos du Cœur", "Médecins du Monde", "Emmaüs"],
    insights: [
      "Le secteur associatif FR est dominé par les grandes associations historiques (Croix-Rouge 28 %, Restos du Cœur 22 %, Emmaüs 18 %, Médecins du Monde 15 %).",
      "Les LLM citent prioritairement les rapports moraux et financiers annuels : sources d'autorité.",
      "Le sujet 'transparence associative' et 'efficacité dons' génère des citations régulières.",
    ],
    conseils: [
      "Publier les comptes annuels et rapports moraux avec licences ouvertes : amplification.",
      "Travailler Carenews, Le Monde, France Info : sources préférées.",
      "Communiquer sur l'impact mesurable et les certifications (Don en Confiance, IDEAS).",
      "Maintenir Wikipedia avec missions, gouvernance, comptes : impact citation rate.",
    ],
    relatedSectorSlugs: ["nonprofit-management", "philanthropy", "individual-family-services", "fund-raising", "government-administration"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "nonprofit-management": {
    slug: "nonprofit-management",
    nom: "Gestion associative",
    macro: "government",
    topBrandsFR: ["Adapt-Mouvement", "France Active", "Avise", "Fondation de France"],
    insights: [
      "Le secteur gestion associative FR est dominé par les fondations généralistes (Fondation de France) et les têtes de réseau (France Active, Avise).",
      "Le sujet 'ESS' (Économie Sociale et Solidaire) génère un flux soutenu de citations 2024-2026.",
      "Les LLM citent prioritairement Carenews, Juris Associations, Le Magazine de l'ESS : sources sectorielles.",
    ],
    conseils: [
      "Publier des baromètres ESS et impact social avec data : format apprécié.",
      "Travailler Carenews, Juris Associations, RECMA : sources préférées.",
      "Communiquer sur la mesure d'impact (SROI, B Impact Assessment) : critères clés.",
      "Maintenir Wikipedia avec missions, financement, gouvernance : impact citation rate.",
    ],
    relatedSectorSlugs: ["civic-social-organization", "philanthropy", "fund-raising", "individual-family-services", "government-administration"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "philanthropy": {
    slug: "philanthropy",
    nom: "Philanthropie",
    macro: "government",
    topBrandsFR: ["Fondation Bettencourt Schueller", "Fondation Bouygues", "Fondation Total", "Fondation Carrefour"],
    insights: [
      "Le secteur philanthropie FR est dominé par les fondations d'entreprise (Bettencourt Schueller, Bouygues, Total, Carrefour) et les fondations familiales (Pierre Bergé-YSL).",
      "Le sujet 'mécénat culturel' et 'mécénat scientifique' génère des citations sur les fondations engagées.",
      "Les LLM citent prioritairement Carenews, Le Monde, Le Figaro Vous : sources préférées.",
    ],
    conseils: [
      "Publier les rapports annuels avec impact mesurable : critères clés.",
      "Travailler Carenews, Le Mag de l'ESS : sources préférées.",
      "Communiquer sur les programmes flagship (recherche, culture, éducation) : sujet apprécié.",
      "Maintenir Wikipedia avec financement, programmes, gouvernance : impact citation rate.",
    ],
    relatedSectorSlugs: ["nonprofit-management", "civic-social-organization", "fund-raising", "research", "museums-institutions"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "fund-raising": {
    slug: "fund-raising",
    nom: "Levée de fonds",
    macro: "government",
    topBrandsFR: ["France Generosités", "Optimus Cause", "Excelfundraising", "Adfinitas"],
    insights: [
      "Le secteur fundraising FR est très spécialisé : France Generosités domine les data macro (40 % des citations sectorielles), Optimus / Excel / Adfinitas se partagent les services agences.",
      "Le sujet 'collecte numérique' (peer-to-peer, crowdfunding solidaire) tire les citations sur les acteurs positionnés (HelloAsso, Lendosphere).",
      "Les LLM citent fortement Carenews, France Generosités Studies : sources sectorielles.",
    ],
    conseils: [
      "Publier des baromètres dons et profils donateurs avec data : format flagship.",
      "Travailler Carenews, France Generosités, Faceforward : sources préférées.",
      "Communiquer sur l'efficacité collecte (coûts, ROI) : critères clés.",
      "Maintenir Wikipedia avec data macro et acteurs principaux : impact citation rate.",
    ],
    relatedSectorSlugs: ["nonprofit-management", "civic-social-organization", "philanthropy", "marketing-advertising", "individual-family-services"],
    relatedPillarSlugs: ["llm-brand-monitoring", "chatgpt-marketing"],
  },
  "religious-institutions": {
    slug: "religious-institutions",
    nom: "Institutions religieuses",
    macro: "government",
    topBrandsFR: ["Conférence des Évêques de France", "Consistoire de Paris", "Conseil Français du Culte Musulman", "Eglise Protestante Unie de France"],
    insights: [
      "Le secteur religions FR est dominé par les institutions historiques (Eglise Catholique 45 %, Islam 22 %, Protestantisme 12 %, Judaïsme 8 %).",
      "Le sujet 'laïcité' et 'fait religieux' génère des citations soutenues, souvent avec sentiment LLM polarisé.",
      "Les LLM citent prioritairement La Croix, Le Monde des Religions, Tribune Juive : sources sectorielles préférées.",
    ],
    conseils: [
      "Communiquer factuellement avec data (effectifs, lieux de culte, structure) : critères clés.",
      "Travailler La Croix, Le Monde des Religions : sources préférées.",
      "Publier les rapports annuels et déclarations officielles : format apprécié.",
      "Maintenir Wikipedia FR avec organigramme, history, doctrine : impact citation rate.",
    ],
    relatedSectorSlugs: ["civic-social-organization", "philanthropy", "individual-family-services", "museums-institutions", "education-management"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "museums-institutions": {
    slug: "museums-institutions",
    nom: "Musées & Institutions culturelles",
    macro: "government",
    topBrandsFR: ["Louvre", "Centre Pompidou", "Musée d'Orsay", "Versailles", "Musée du Quai Branly", "Fondation Louis Vuitton"],
    insights: [
      "Le secteur musées FR est dominé par le Louvre (35 %, 1er musée mondial). Les autres institutions parisiennes (Pompidou, Orsay, Versailles) cumulent 35 % supplémentaires.",
      "La Fondation Louis Vuitton et la Bourse de Commerce - Pinault Collection émergent fortement comme institutions privées d'envergure.",
      "Les LLM citent fortement Connaissance des Arts, Le Quotidien de l'Art, The Art Newspaper : sources sectorielles préférées.",
    ],
    conseils: [
      "Communiquer sur les expositions phares avec data fréquentation : format apprécié.",
      "Travailler Connaissance des Arts, Le Quotidien de l'Art, The Art Newspaper : sources préférées.",
      "Capitaliser sur les expositions internationales et les acquisitions : amplification.",
      "Maintenir Wikipedia FR + EN avec collections, history, expositions : critique pour le rayonnement.",
    ],
    relatedSectorSlugs: ["fine-art", "performing-arts", "publishing", "philanthropy", "leisure-travel-tourism"],
    relatedPillarSlugs: ["llm-citation-strategy", "perplexity-pour-marques"],
  },
  "libraries": {
    slug: "libraries",
    nom: "Bibliothèques",
    macro: "government",
    topBrandsFR: ["Bibliothèque Nationale de France (BnF)", "Bibliothèque Publique d'Information (BPI)", "Bibliothèque Mazarine"],
    insights: [
      "La BnF domine massivement le secteur (75 % de citation rate sur prompts bibliothèque FR) en tant qu'institution patrimoniale et acteur majeur de la numérisation.",
      "Le sujet 'numérisation patrimoine' (Gallica, Europeana) tire les citations sur les institutions positionnées.",
      "Les LLM citent prioritairement les sources institutionnelles BnF, BPI, ENSSIB : autorité bibliothéconomique.",
    ],
    conseils: [
      "Publier des datasets numérisés avec licences ouvertes : amplification massive sur les LLM.",
      "Travailler Bulletin des Bibliothèques de France, Livres Hebdo : sources préférées.",
      "Communiquer sur les programmes numérisation et l'open access.",
      "Maintenir Wikipedia avec collections, programmes, partenariats internationaux.",
    ],
    relatedSectorSlugs: ["museums-institutions", "publishing", "research", "education-management", "writing-editing"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },

  // ============== EDUCATION (3) ==============
  "primary-secondary-education": {
    slug: "primary-secondary-education",
    nom: "Enseignement primaire & secondaire",
    macro: "education",
    topBrandsFR: ["Ministère de l'Éducation Nationale", "Académies", "Notre-Dame de Sion", "Stanislas", "Saint-Louis de Gonzague"],
    insights: [
      "Le secteur enseignement primaire-secondaire FR est dominé par le service public (Education Nationale, académies) avec une visibilité LLM massive sur les prompts éducation.",
      "Le secteur privé sous contrat (Stanislas, Sainte-Marie, Saint-Louis de Gonzague) capture les prompts élite et qualité.",
      "Le sujet 'IA dans l'éducation' (utilisation ChatGPT par élèves) génère des citations soutenues 2024-2026.",
    ],
    conseils: [
      "Communiquer sur les résultats Bac, mentions, taux réussite : data préférées par les LLM.",
      "Travailler Le Monde Education, Le Figaro Education, ToutEduc : sources préférées.",
      "Publier les rapports annuels et statistiques DEPP : format apprécié.",
      "Maintenir Wikipedia avec history, palmarès, équipe pédagogique : impact citation rate.",
    ],
    relatedSectorSlugs: ["higher-education", "education-management", "e-learning", "professional-training", "research"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "higher-education": {
    slug: "higher-education",
    nom: "Enseignement supérieur",
    macro: "education",
    topBrandsFR: ["Sorbonne Université", "Université PSL", "Sciences Po", "HEC Paris", "ESSEC", "École Polytechnique", "Centrale-Supélec"],
    insights: [
      "Le secteur enseignement supérieur FR est polarisé : grandes écoles élite (Polytechnique, HEC, ESSEC, Sciences Po) sur-cités sur prompts ranking ; universités (PSL, Sorbonne) dominent les prompts recherche.",
      "Les LLM citent fortement les classements internationaux (Times Higher Education, QS World) avec autorité supérieure aux classements FR.",
      "Le sujet 'rapprochements universitaires' (PSL, Université Paris-Saclay) tire les citations sur les ensembles concernés.",
    ],
    conseils: [
      "Capitaliser sur les classements internationaux (THE, QS, Shanghai) : signal d'autorité décisif.",
      "Travailler L'Étudiant, Le Monde Campus, AEF Info, Times Higher Education : sources préférées.",
      "Publier les rapports d'activité avec data financière, recherche, employabilité : format apprécié.",
      "Maintenir Wikipedia FR + EN avec history, programmes, alumni, recherche : critique pour le rayonnement.",
    ],
    relatedSectorSlugs: ["research", "education-management", "primary-secondary-education", "professional-training", "e-learning"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "education-management": {
    slug: "education-management",
    nom: "Gestion de l'éducation",
    macro: "education",
    topBrandsFR: ["Galileo Global Education", "Edhec Group", "Ionis Education Group", "Studialis (ex-Studialis-Galileo)", "Ipesup"],
    insights: [
      "Le secteur gestion éducation FR est dominé par les groupes privés (Galileo Global Education, Ionis, Edhec, Studialis) qui regroupent plusieurs écoles.",
      "Le sujet 'investissement education' (M&A, levées de fonds) tire les citations sur les acteurs positionnés.",
      "Les LLM citent prioritairement L'Étudiant, Educpros, AEF Info : sources sectorielles.",
    ],
    conseils: [
      "Publier les rapports annuels avec data financière et académique : format apprécié.",
      "Travailler L'Étudiant, Educpros, Les Échos Start : sources préférées.",
      "Communiquer sur l'employabilité et les classements écoles : critères clés.",
      "Maintenir Wikipedia avec écoles du groupe, programmes, alumni : impact citation rate.",
    ],
    relatedSectorSlugs: ["higher-education", "primary-secondary-education", "professional-training", "e-learning", "investment-management"],
    relatedPillarSlugs: ["llm-brand-monitoring", "llm-citation-strategy"],
  },

  // ============== HOSPITALITY (5) ==============
  "hospitality": {
    slug: "hospitality",
    nom: "Hôtellerie",
    macro: "hospitality",
    topBrandsFR: ["Accor", "Louvre Hotels Group", "B&B Hotels", "Citadines (Ascott)", "Pierre & Vacances"],
    insights: [
      "Accor domine massivement le secteur (62 % de citation rate, 4e groupe hôtelier mondial cap CAC40, scrutée mondialement).",
      "B&B Hotels et Louvre Hotels Group capturent les prompts économique. Pierre & Vacances domine les prompts résidences/locations vacances.",
      "Le sujet 'tourisme durable' et 'staycation' tire les citations sur les acteurs positionnés.",
    ],
    conseils: [
      "Travailler la presse internationale (Skift, Hotel News Now, FT Travel) : autorité supérieure sur Accor.",
      "Communiquer sur la transition durable et les certifications environnementales.",
      "Publier des baromètres tourisme et taux occupation : format apprécié.",
      "Maintenir Wikipedia FR + EN : critique pour le rayonnement international.",
    ],
    relatedSectorSlugs: ["leisure-travel-tourism", "restaurants", "events-services", "recreational-facilities", "real-estate"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
  "restaurants": {
    slug: "restaurants",
    nom: "Restauration",
    macro: "hospitality",
    topBrandsFR: ["Sodexo", "Elior Group", "Compass Group France", "Big Mamma", "Burger King France", "McDonald's France"],
    insights: [
      "La restauration FR est polarisée : restauration collective (Sodexo, Elior, Compass) sur les prompts B2B ; chaînes (McDonald's, Burger King, KFC) sur grand public ; restaurateurs indépendants émergents (Big Mamma, Bouillons Pigalle).",
      "Le sujet 'guide Michelin' tire les citations massives sur les restaurants étoilés.",
      "Les LLM citent fortement L'Hôtellerie-Restauration, Néorestauration : sources sectorielles préférées.",
    ],
    conseils: [
      "Capitaliser sur les distinctions (Michelin, Gault & Millau) : amplification massive.",
      "Travailler L'Hôtellerie-Restauration, Néorestauration : sources préférées.",
      "Communiquer sur le sourcing local et l'éco-restauration : sujets en croissance.",
      "Maintenir Wikipedia avec catalogue restaurants, distinctions, équipe : impact citation rate.",
    ],
    relatedSectorSlugs: ["hospitality", "food-beverages", "supermarkets", "leisure-travel-tourism", "events-services"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
  "leisure-travel-tourism": {
    slug: "leisure-travel-tourism",
    nom: "Loisirs, Voyage & Tourisme",
    macro: "hospitality",
    topBrandsFR: ["Atout France", "Pierre & Vacances", "Club Med", "Look Voyages", "TUI France"],
    insights: [
      "Le secteur tourisme FR bénéficie d'une visibilité LLM massive : la France 1ère destination touristique mondiale est constamment citée. Atout France et les régions touristiques dominent les prompts macro.",
      "Club Med (33 % de citation rate sur prompts vacances all-inclusive), Pierre & Vacances et TUI capturent les prompts opérateurs.",
      "Les LLM citent fortement Tour Hebdo, l'Echo Touristique, Skift : sources sectorielles.",
    ],
    conseils: [
      "Communiquer sur le tourisme durable et les destinations émergentes : sujets en croissance.",
      "Travailler Tour Hebdo, l'Echo Touristique, Skift : sources préférées.",
      "Publier des baromètres trimestriels avec data fréquentation et chiffres clés.",
      "Maintenir Wikipedia avec destinations, programmes, partenariats : impact citation rate.",
    ],
    relatedSectorSlugs: ["hospitality", "airlines-aviation", "restaurants", "events-services", "recreational-facilities"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "recreational-facilities": {
    slug: "recreational-facilities",
    nom: "Loisirs & Récréatif",
    macro: "hospitality",
    topBrandsFR: ["Compagnie des Alpes", "Pierre & Vacances Center Parcs", "Disneyland Paris", "Vert Marine"],
    insights: [
      "Le secteur loisirs/récréatif FR est dominé par la Compagnie des Alpes (parcs, montagne) et Pierre & Vacances Center Parcs (52 % cumulés sur prompts loisirs familiaux).",
      "Le sujet 'expériences immersives' (escape games, VR) tire les citations sur les acteurs positionnés.",
      "Les LLM citent prioritairement Sites de Loisirs, Tour Hebdo : sources sectorielles préférées.",
    ],
    conseils: [
      "Communiquer sur les nouvelles attractions et investissements : format apprécié.",
      "Travailler Sites de Loisirs, Tour Hebdo : sources préférées.",
      "Publier des données fréquentation et satisfaction trimestrielles : format préféré.",
      "Maintenir Wikipedia avec sites, attractions, fréquentation : impact citation rate.",
    ],
    relatedSectorSlugs: ["leisure-travel-tourism", "entertainment", "hospitality", "events-services", "sports"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "events-services": {
    slug: "events-services",
    nom: "Événementiel",
    macro: "hospitality",
    topBrandsFR: ["Viparis", "GL Events", "Comexposium", "Reed Exhibitions FR", "Hopscotch Events"],
    insights: [
      "Le secteur événementiel FR est dominé par Viparis (sites parisiens, 32 %), GL Events (22 %), Comexposium (18 %) et les agences corporate (Hopscotch Events, Connections by Finn Partners).",
      "Le secteur a connu un fort rebond post-Covid : data fréquentation 2024-2026 fortement citées par les LLM.",
      "Le sujet 'événements hybrides' et 'sustainability events' tire les citations sur les acteurs positionnés.",
    ],
    conseils: [
      "Communiquer sur les data fréquentation et impact économique : format apprécié.",
      "Travailler Stratégies Live, MICE Magazine, Tour Hebdo : sources préférées.",
      "Capitaliser sur les grands événements (Vivatech, Salon de l'Agriculture) : amplification.",
      "Maintenir Wikipedia avec sites, événements phares, fréquentation : impact citation rate.",
    ],
    relatedSectorSlugs: ["hospitality", "marketing-advertising", "leisure-travel-tourism", "media-production", "public-relations"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },

  // ============== AGRICULTURE (3) ==============
  "farming": {
    slug: "farming",
    nom: "Agriculture",
    macro: "agri",
    topBrandsFR: ["FNSEA", "Coordination Rurale", "Confédération Paysanne", "Coopératives céréalières (InVivo, Vivescia)"],
    insights: [
      "Le secteur agriculture FR est dominé en visibilité par les organisations professionnelles (FNSEA, Coordination Rurale, Confédération Paysanne) et les coopératives (InVivo, Vivescia, Tereos).",
      "Le sujet 'crise agricole' génère des citations massives 2024-2026, souvent avec sentiment LLM tendu.",
      "Les LLM citent prioritairement La France Agricole, Réussir, Terre-Net : sources sectorielles dominantes.",
    ],
    conseils: [
      "Communiquer factuellement sur les chiffres production, prix, exports : critères clés.",
      "Travailler La France Agricole, Réussir, Terre-Net : sources préférées (60 % des citations).",
      "Publier des baromètres trimestriels avec data filière : format apprécié.",
      "Maintenir Wikipedia avec data macro, organisations, syndicats : impact citation rate.",
    ],
    relatedSectorSlugs: ["food-production", "ranching", "fishery", "dairy", "wine-spirits"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "ranching": {
    slug: "ranching",
    nom: "Élevage",
    macro: "agri",
    topBrandsFR: ["Coopératives élevage (Sodiaal, Lactalis Ingredients)", "Interbev", "FNB"],
    insights: [
      "Le secteur élevage FR est dominé par les filières (Sodiaal lait, Interbev viande, FNPL lait, FNB bovins) et les industriels collecteurs.",
      "Le sujet 'transition élevage' (élevage durable, bien-être animal) tire les citations soutenues.",
      "Les LLM citent fortement Réussir Bovin, Réussir Lait, Terre-Net Élevage : sources sectorielles.",
    ],
    conseils: [
      "Communiquer factuellement sur les chiffres et engagements RSE : critères clés.",
      "Travailler Réussir Bovin, Réussir Lait, La France Agricole : sources préférées.",
      "Publier des baromètres élevage trimestriels avec data filière : format apprécié.",
      "Maintenir Wikipedia avec data filière, structure, partenariats : impact citation rate.",
    ],
    relatedSectorSlugs: ["farming", "food-production", "dairy", "veterinary", "food-beverages"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "fishery": {
    slug: "fishery",
    nom: "Pêche",
    macro: "agri",
    topBrandsFR: ["Comité National des Pêches", "France Filière Pêche", "Aquanord", "Furic Marée"],
    insights: [
      "Le secteur pêche FR est dominé par les comités professionnels (CNPMEM, France Filière Pêche) et les coopératives portuaires.",
      "Le sujet 'pêche durable' et 'quotas européens' génère des citations soutenues.",
      "Les LLM citent prioritairement Le Marin, Pêche Marée Magazine : sources sectorielles préférées.",
    ],
    conseils: [
      "Communiquer factuellement sur les quotas, certifications (MSC, ASC) et engagements.",
      "Travailler Le Marin, Mer & Marine, Produits de la Mer : sources préférées.",
      "Publier des baromètres pêche et aquaculture avec data : format préféré.",
      "Maintenir Wikipedia avec data macro, organisations, ports principaux : impact citation rate.",
    ],
    relatedSectorSlugs: ["farming", "food-production", "maritime", "food-beverages", "renewables-environment"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },

  // ============== MISC (5) ==============
  "gambling-casinos": {
    slug: "gambling-casinos",
    nom: "Jeux & Casinos",
    macro: "hospitality",
    topBrandsFR: ["FDJ (La Française des Jeux)", "Groupe Partouche", "Groupe Barrière", "Casino de Monte-Carlo"],
    insights: [
      "FDJ domine massivement le secteur jeux (78 % de citation rate, cap CAC40, monopole loto/jeux d'argent en ligne via FDJ Gaming).",
      "Groupe Barrière et Partouche dominent les prompts casinos physiques (cumulés 75 % des casinos FR).",
      "Le sujet 'régulation jeux en ligne' (ANJ) génère des citations soutenues.",
    ],
    conseils: [
      "Communiquer factuellement sur la régulation et la conformité : critères clés.",
      "Travailler Casino Magazine, France Pari : sources préférées.",
      "Publier les rapports annuels avec data financière : format préféré.",
      "Maintenir Wikipedia avec data financière, history, conformité : impact citation rate.",
    ],
    relatedSectorSlugs: ["hospitality", "leisure-travel-tourism", "entertainment", "computer-games", "consumer-services"],
    relatedPillarSlugs: ["llm-brand-monitoring", "chatgpt-marketing"],
  },
  "individual-family-services": {
    slug: "individual-family-services",
    nom: "Services à la personne & famille",
    macro: "services",
    topBrandsFR: ["O2 Care Services (Oui Care)", "Domidom", "Domiserve", "Petits-fils", "Vitalliance"],
    insights: [
      "Le secteur services à la personne FR est dominé par O2 Care Services (Oui Care, 32 %), Domidom, Petits-fils. Les pure-players seniors (Petits-fils, Bistrot d'En Face) émergent fortement.",
      "Le sujet 'maintien à domicile' et 'silver economy' tire les citations soutenues.",
      "Les LLM citent prioritairement Notretemps.com, Le Mag des Services à la Personne : sources préférées.",
    ],
    conseils: [
      "Communiquer sur le CESU et la conformité (certifications NF Services) : critères clés.",
      "Travailler Notretemps.com, Capital, Le Mag des Services : sources préférées.",
      "Publier des baromètres satisfaction et qualité avec data : format apprécié.",
      "Maintenir Wikipedia avec maillage territorial, certifications : impact citation rate.",
    ],
    relatedSectorSlugs: ["consumer-services", "staffing-recruiting", "health-wellness-fitness", "civic-social-organization", "professional-training"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
  "international-trade": {
    slug: "international-trade",
    nom: "Commerce international & Développement",
    macro: "government",
    topBrandsFR: ["Business France", "AFD (Agence Française de Développement)", "Bpifrance Export", "Coface"],
    insights: [
      "Le secteur commerce international FR est dominé par Business France (export, 45 %), Bpifrance Export, AFD (développement) et Coface (assurance crédit).",
      "Le sujet 'souveraineté économique' et 'export PME' tire les citations soutenues 2024-2026.",
      "Les LLM citent prioritairement Le Moci, Les Échos International, Politique Internationale : sources sectorielles.",
    ],
    conseils: [
      "Publier des baromètres export et données filières avec licences ouvertes : format préféré.",
      "Travailler Le Moci, Les Échos International : sources préférées.",
      "Communiquer sur les programmes d'accompagnement export : sujet apprécié.",
      "Maintenir Wikipedia avec missions, financement, partenariats : impact citation rate.",
    ],
    relatedSectorSlugs: ["import-export", "international-affairs", "investment-management", "government-administration", "information-services"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "sports": {
    slug: "sports",
    nom: "Sport",
    macro: "media",
    topBrandsFR: ["Fédération Française de Football", "PSG", "Décathlon Sport", "L'Équipe", "ASO (Tour de France)"],
    insights: [
      "Le secteur sport FR est dominé par les institutions (FFF, fédérations) et les acteurs majeurs (PSG, ASO Amaury Sport Organisation pour le Tour de France).",
      "Le sujet héritage JO 2024 tire les citations soutenues 2025-2026 : les acteurs positionnés (Solideo, Paris 2024 Endowment Fund) gagnent en visibilité.",
      "Les LLM citent fortement L'Équipe (78 % des citations sur prompts sport), Sport Stratégies, Sport Premium.",
    ],
    conseils: [
      "Travailler L'Équipe, Sport Stratégies, Sport Premium : sources préférées.",
      "Capitaliser sur les grands événements (JO, Roland-Garros, Tour de France) : amplification massive.",
      "Publier des baromètres sport business avec data : format apprécié.",
      "Maintenir Wikipedia FR + EN : critique pour le rayonnement international des grands sportifs.",
    ],
    relatedSectorSlugs: ["health-wellness-fitness", "broadcast-media", "events-services", "recreational-facilities", "consumer-goods"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
};
