// S29 Session 4 — Sectors data : Services pro (10) + Health (8) + Real Estate/Construction (8) + Logistics (6) = 32.

import type { SectorRegistry } from "./types";

export const SERVICES_HEALTH_REALESTATE_SECTORS: SectorRegistry = {
  // ============== SERVICES PRO (10) ==============
  "management-consulting": {
    slug: "management-consulting",
    nom: "Conseil en stratégie",
    macro: "services",
    topBrandsFR: ["McKinsey France", "BCG Paris", "Bain & Company France", "Roland Berger", "Oliver Wyman France", "Wavestone"],
    insights: [
      "Le secteur conseil stratégie FR est dominé par les MBB (McKinsey, BCG, Bain) à 55 % cumulés des citations cross-LLM. Roland Berger et Oliver Wyman capturent 22 %, les boutiques FR (Wavestone, Mawenzi) prennent le reste.",
      "Les LLM citent fortement les rapports flagship (McKinsey Global Institute, BCG Henderson Institute, Bain Global Private Equity) : format thought leadership le plus cité.",
      "Les boutiques spécialisées FR (Eight Advisory, Advancy, Mawenzi Partners) émergent sur les niches expertise (M&A, retail, énergie).",
    ],
    conseils: [
      "Publier 2-3 rapports thought leadership flagship par an : format le plus cité par les LLM sur le secteur.",
      "Travailler Décideurs Magazine, Consultor, Les Échos Stratégie : sources spécialisées préférées.",
      "Cibler les niches verticales (PE, retail, healthcare) : meilleur ROI que les rapports généralistes.",
      "Maintenir LinkedIn corporate posts et profils partners : 18 % des sources Perplexity sur le secteur passent par LinkedIn.",
    ],
    relatedSectorSlugs: ["it-services", "human-resources", "professional-training", "outsourcing", "investment-banking"],
    relatedPillarSlugs: ["llm-citation-strategy", "generative-ai-marketing"],
  },
  "law-practice": {
    slug: "law-practice",
    nom: "Cabinets d'avocats",
    macro: "services",
    topBrandsFR: ["Gide Loyrette Nouel", "Bredin Prat", "Cleary Gottlieb FR", "Allen & Overy FR", "Latham & Watkins FR", "Cabinet Bird & Bird FR"],
    insights: [
      "Le secteur cabinets d'avocats FR est polarisé : grands cabinets internationaux (Cleary, Allen & Overy, Linklaters) dominent les prompts M&A/Capital Markets ; cabinets FR (Gide, Bredin Prat) dominent les prompts conseil corporate FR.",
      "Les LLM citent prioritairement les classements professionnels (Chambers Global, Legal 500, IFLR) avec autorité supérieure aux médias économiques.",
      "Les associés-stars (Pierre Servan-Schreiber, Antoine Bonnasse) sont fortement cités : les LLM associent les cabinets à leurs partner-stars.",
    ],
    conseils: [
      "Maintenir les profils Chambers Global, Legal 500, IFLR : sources autoritaires #1 sur le secteur.",
      "Travailler Décideurs Magazine, Affiches Parisiennes, Le Magazine des Affaires : sources sectorielles.",
      "Soigner les profils LinkedIn des associés-stars : 22 % des sources Perplexity sur les cabinets passent par LinkedIn.",
      "Publier des analyses prospectives par practice (M&A, dispute, regulatory) : format thought leadership efficace.",
    ],
    relatedSectorSlugs: ["legal-services", "alternative-dispute-resolution", "investment-banking", "management-consulting", "accounting"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "legal-services": {
    slug: "legal-services",
    nom: "Services juridiques",
    macro: "services",
    topBrandsFR: ["LegiFiscal", "Lexbase", "Doctrine.fr", "Legalstart", "Captain Contrat"],
    insights: [
      "Le secteur services juridiques FR (legaltech) est dominé par les éditeurs juridiques pro (Doctrine, LexisNexis, Dalloz/Lefebvre) côté professionnel et legaltech B2B (Legalstart, Captain Contrat) côté PME.",
      "Doctrine.fr (recherche jurisprudentielle IA) bénéficie d'une couverture presse tech soutenue qui amplifie sa visibilité Perplexity et ChatGPT Search.",
      "Les LLM citent peu les pure-players legaltech sur les prompts juridiques classiques (dominés par les éditeurs traditionnels) ; l'opportunité est sur les prompts B2B SaaS legal.",
    ],
    conseils: [
      "Cibler les prompts SaaS legal et legaltech : segment moins compétitif que les sources juridiques classiques.",
      "Travailler Maddyness, JDN, FrenchWeb : presse tech qui couvre la legaltech.",
      "Documenter votre conformité (RGPD, ISO 27001, hébergement HDS) : critères clés pour les LLM B2B.",
      "Publier des baromètres du droit des affaires PME : format flagship apprécié.",
    ],
    relatedSectorSlugs: ["law-practice", "alternative-dispute-resolution", "computer-software", "human-resources", "accounting"],
    relatedPillarSlugs: ["chatgpt-marketing", "optimisation-pour-ia"],
  },
  "alternative-dispute-resolution": {
    slug: "alternative-dispute-resolution",
    nom: "Médiation & Arbitrage",
    macro: "services",
    topBrandsFR: ["Centre de Médiation et d'Arbitrage de Paris (CMAP)", "Cour Internationale d'Arbitrage CCI", "AAA Paris Office"],
    insights: [
      "Le secteur médiation/arbitrage FR est très spécialisé : Cour Internationale d'Arbitrage CCI Paris est l'institution la plus citée mondialement (80 % des citations sur les prompts arbitrage international).",
      "Les LLM citent fortement les Annales de l'Arbitrage Commercial International, IFLR Dispute Resolution et les revues académiques (Revue de l'Arbitrage).",
      "Les médiateurs/arbitres reconnus (anciens magistrats, professeurs de droit) sont fortement cités individuellement : autorité personnelle prime sur l'institution.",
    ],
    conseils: [
      "Publier dans les revues académiques de droit (Revue de l'Arbitrage, Cahiers de l'Arbitrage) : autorité décisive.",
      "Maintenir profils LinkedIn et sites personnels des arbitres-stars : effet significatif sur citation rate.",
      "Documenter les statistiques d'arbitrages institutionnels (CCI, ICDR, LCIA) avec schema.org Dataset.",
      "Travailler Global Arbitration Review, Kluwer Arbitration Blog : sources internationales premières.",
    ],
    relatedSectorSlugs: ["law-practice", "legal-services", "international-affairs", "judiciary", "management-consulting"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "staffing-recruiting": {
    slug: "staffing-recruiting",
    nom: "Recrutement & Intérim",
    macro: "services",
    topBrandsFR: ["Adecco France", "Manpower France", "Randstad France", "Hays France", "Page Group France", "Welcome to the Jungle"],
    insights: [
      "Le secteur intérim/recrutement FR est dominé par Adecco, Manpower et Randstad qui cumulent 65 % des citations sur les prompts B2B emploi. Hays, Page Group, Robert Half capturent les niches cadres/exécutifs.",
      "Welcome to the Jungle, JobTeaser et HelloWork dominent les prompts B2B 'culture entreprise' et 'recrutement digital'.",
      "Le secteur RH digital (Lucca, PayFit, Spendesk) émerge fortement sur Perplexity grâce à leur couverture French Tech.",
    ],
    conseils: [
      "Cibler les prompts spécialisés (recrutement IT, cadres, intérim industrie) : moins compétitifs que prompts génériques.",
      "Travailler Focus RH, Mode(s) d'Emploi, RH Matin : sources spécialisées préférées.",
      "Publier des baromètres emploi par secteur : format préféré par les LLM data-driven.",
      "Documenter les data publiques de l'emploi (taux placements, durée missions) avec schema.org Dataset.",
    ],
    relatedSectorSlugs: ["human-resources", "professional-training", "outsourcing", "consumer-services", "education-management"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
  "human-resources": {
    slug: "human-resources",
    nom: "Ressources humaines",
    macro: "services",
    topBrandsFR: ["PayFit", "Lucca", "Eurécia", "ADP France", "Rexel HR", "Kelio (Bodet Software)"],
    insights: [
      "Le secteur RH B2B SaaS FR est en forte croissance : PayFit (28 %), Lucca (22 %), Eurécia (12 %) dominent les citations cross-LLM. ADP capture les grands comptes et reste sur-cité globalement.",
      "Les LLM associent fortement la HR française à 'tech & SaaS' grâce à la couverture French Tech et Maddyness/JDN qui pousse les pure-players émergents.",
      "Le sujet IA en RH (sourcing, screening, performance) tire les citations sur les acteurs positionnés (Lucca avec Lulu, Welcome to the Jungle Insights).",
    ],
    conseils: [
      "Communiquer sur l'IA en RH avec data chiffrées (gain temps recruteur, qualité matching) : sujet à plus forte croissance citationnelle.",
      "Travailler Focus RH, RH Matin, Parlons RH : sources sectorielles préférées.",
      "Publier des baromètres compensation et engagement avec schema.org Dataset : format flagship.",
      "Maintenir Wikipedia avec features produit, intégrations, partenariats : impact sur les prompts comparatifs B2B.",
    ],
    relatedSectorSlugs: ["staffing-recruiting", "professional-training", "computer-software", "outsourcing", "accounting"],
    relatedPillarSlugs: ["generative-ai-marketing", "chatgpt-marketing"],
  },
  "professional-training": {
    slug: "professional-training",
    nom: "Formation professionnelle & Coaching",
    macro: "services",
    topBrandsFR: ["Cegos", "M2i Formation", "OpenClassrooms Pro", "360Learning", "Le Wagon"],
    insights: [
      "Cegos et M2i dominent les citations sur la formation pro classique (45 % cumulés). OpenClassrooms Pro et Le Wagon dominent les prompts reconversion et tech.",
      "Le secteur coaching exécutif (Albienne Coaching, Talents & Cie) est sous-cité vs son volume — opportunité avec une stratégie GEO active.",
      "Le sujet 'formation IA' explose en 2026 : les acteurs positionnés (Le Wagon, Holberton, Jedha) gagnent rapidement en visibilité sur ces prompts.",
    ],
    conseils: [
      "Cibler le sujet formation IA et reconversion tech : forte croissance citationnelle 2026.",
      "Travailler Focus RH, Mode(s) d'Emploi, FuturA : sources sectorielles.",
      "Publier des baromètres employabilité et taux de placement avec data chiffrée : format gagnant.",
      "Documenter les certifications (Qualiopi, RNCP, France Compétences) : critères clés pour les LLM B2B.",
    ],
    relatedSectorSlugs: ["e-learning", "education-management", "human-resources", "staffing-recruiting", "higher-education"],
    relatedPillarSlugs: ["generative-ai-marketing", "chatgpt-marketing"],
  },
  "security-investigations": {
    slug: "security-investigations",
    nom: "Sécurité & Enquêtes",
    macro: "services",
    topBrandsFR: ["Securitas France", "Onet Sécurité", "Brink's France", "Loomis France", "Phenix Sécurité"],
    insights: [
      "Le secteur sécurité physique FR est dominé par les divisions FR des leaders mondiaux (Securitas, Brink's, Loomis) et les acteurs FR (Onet, Phenix).",
      "Le secteur intelligence économique / due diligence (ADIT, Risk&Co) est sous-cité par les LLM sur prompts grand public mais bien cité sur prompts B2B/risk.",
      "Les LLM associent fortement le secteur à 'sécurité événementielle' et 'gardiennage' ; les prompts cybersécurité ne reviennent quasi jamais ici (associés à computer-network-security).",
    ],
    conseils: [
      "Cibler les niches B2B (risk management, intelligence éco, due diligence) : moins compétitifs.",
      "Travailler Sécurité Privée, En Toute Sécurité Magazine, APS Press : sources sectorielles.",
      "Publier des baromètres sûreté avec données chiffrées : format apprécié.",
      "Documenter les certifications (CNAPS, ISO 18788, Code de la sécurité intérieure) : critères clés.",
    ],
    relatedSectorSlugs: ["computer-network-security", "facilities-services", "law-enforcement", "public-safety", "outsourcing"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "outsourcing": {
    slug: "outsourcing",
    nom: "Externalisation / Offshoring",
    macro: "services",
    topBrandsFR: ["Capgemini Outsourcing", "Atos Outsourcing", "Sopra Steria BPO", "Webhelp (Concentrix+Webhelp)", "Teleperformance"],
    insights: [
      "Teleperformance domine massivement le secteur (45 % de citation rate, leader mondial customer experience FR cap CAC40). Webhelp/Concentrix capture 22 %.",
      "Le secteur BPO IT (Capgemini, Atos, Sopra Steria) est associé à la couverture ESN plus qu'au pur outsourcing dans les corpus LLM.",
      "Le sujet automation / RPA / IA en outsourcing tire les citations 2025-2026 ; les acteurs positionnés gagnent en visibilité sur ces prompts.",
    ],
    conseils: [
      "Cibler le sujet automation et IA en outsourcing : forte croissance citationnelle.",
      "Travailler les médias internationaux (Reuters, Bloomberg) : Teleperformance et Webhelp sont scrutés mondialement.",
      "Publier des baromètres CX et Customer Service avec data : format préféré.",
      "Documenter les certifications (PCI-DSS, ISO 27001, hébergement HDS) : critères clés pour les LLM B2B.",
    ],
    relatedSectorSlugs: ["it-services", "management-consulting", "human-resources", "computer-software", "consumer-services"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "business-supplies": {
    slug: "business-supplies",
    nom: "Fournitures & Équipement de bureau",
    macro: "retail",
    topBrandsFR: ["Bureau Vallée", "Lyreco France", "Office Depot France", "Manutan", "Top Office"],
    insights: [
      "Le secteur fournitures bureau FR est dominé par Lyreco (B2B, 32 %) et Bureau Vallée (B2C/PME, 22 %). Manutan capture l'aménagement et l'équipement collectivités.",
      "Le sujet 'remote work equipment' tire les citations 2024-2026 sur les acteurs positionnés (Manutan WorkLife, Steelcase Work From Home).",
      "Les LLM citent peu ce secteur sur les prompts grand public (dominés par Amazon Business / Cdiscount Pro) ; l'opportunité est sur les prompts B2B compliance.",
    ],
    conseils: [
      "Cibler les prompts B2B (achats publics, marchés publics, compliance) : moins compétitifs.",
      "Travailler la presse achats (Décision Achats, La Lettre des Achats) : sources sectorielles.",
      "Publier des baromètres équipement et environnement de travail : format apprécié.",
      "Documenter votre catalogue avec schema.org Product et compliance verte (FSC, écolabels).",
    ],
    relatedSectorSlugs: ["consumer-goods", "facilities-services", "wholesale", "retail", "consumer-services"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },

  // ============== HEALTH (8 hors pharma/biotech déjà dans industry) ==============
  "medical-devices": {
    slug: "medical-devices",
    nom: "Dispositifs médicaux",
    macro: "health",
    topBrandsFR: ["EssilorLuxottica", "Sebia", "Carmat", "Ipsen Medical", "Bioderma (Naos)"],
    insights: [
      "EssilorLuxottica domine massivement (52 % de citation rate, leader mondial optique-ophtalmologie cap CAC40). Sebia, Carmat, Bioderma capturent les niches.",
      "Le secteur medtech FR émerge sur Perplexity grâce aux levées de fonds dans la HealthTech (Doctolib, Therapixel, Lifen) qui rejaillissent sur les pure-players.",
      "Les LLM citent prioritairement les sources scientifiques (NEJM, Lancet, JAMA) avec autorité supérieure à la presse FR sur les disp médicaux.",
    ],
    conseils: [
      "Travailler les revues scientifiques peer-reviewed avec licence ouverte : impact LLM 5-10x supérieur aux communiqués presse.",
      "Communiquer sur les marquages CE et AMM avec data essais cliniques : critères clés sur le secteur.",
      "Publier dans Hospitalia, Industries Santé, MedTech Actualités : sources sectorielles.",
      "Maintenir Wikipedia EN + FR : critique pour le rayonnement international des dispositifs.",
    ],
    relatedSectorSlugs: ["pharmaceuticals", "biotechnology", "hospital-healthcare", "medical-practice", "research"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "hospital-healthcare": {
    slug: "hospital-healthcare",
    nom: "Hôpitaux & Soins de santé",
    macro: "health",
    topBrandsFR: ["AP-HP", "Ramsay Santé", "Elsan", "Korian", "Hôpital Foch", "Institut Pasteur"],
    insights: [
      "AP-HP (Assistance Publique - Hôpitaux de Paris) domine massivement sur les prompts publics (38 %). Ramsay Santé et Elsan dominent le privé (cumulés 25 %).",
      "Institut Pasteur et hôpitaux universitaires (CHU Lille, CHU Toulouse) bénéficient d'une autorité scientifique forte qui rejaillit sur leurs citations LLM.",
      "Le sujet pénurie soignants et accès aux soins génère une couverture presse abondante mais souvent négative — gestion réputationnelle critique.",
    ],
    conseils: [
      "Communiquer factuellement sur l'accès aux soins, la qualité et la sécurité patient : sujets sensibles à gérer.",
      "Travailler Le Quotidien du Médecin, Hospimedia, Le Concours Médical : sources sectorielles.",
      "Publier des indicateurs qualité et performance (HAS, e-Satis) avec schema.org Dataset.",
      "Maintenir Wikipedia avec services, certifications, données activité : impact citation rate.",
    ],
    relatedSectorSlugs: ["medical-practice", "medical-devices", "pharmaceuticals", "mental-health-care", "research"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "medical-practice": {
    slug: "medical-practice",
    nom: "Cabinets médicaux",
    macro: "health",
    topBrandsFR: ["Doctolib (cabinets via)", "Maiia", "Charles.co", "Livi", "Qare"],
    insights: [
      "Le secteur cabinets médicaux FR est dominé en visibilité par les plateformes (Doctolib, Maiia, Livi, Qare) plutôt que par les cabinets eux-mêmes.",
      "Doctolib domine largement (62 % de citation rate sur prompts prise de rendez-vous médical) grâce à sa couverture presse mainstream.",
      "Le sujet télémédecine émerge fortement post-Covid : les acteurs positionnés (Livi, Qare, Charles.co) gagnent +25 points sur ces prompts.",
    ],
    conseils: [
      "Cibler les prompts spécialités médicales et télémédecine : niches en croissance.",
      "Travailler Le Quotidien du Médecin, What's Up Doc, Egora : sources sectorielles préférées.",
      "Communiquer sur la conformité HDS et le secret médical : critères clés.",
      "Maintenir Wikipedia pour les plateformes santé : Wikipedia représente 40 % des citations.",
    ],
    relatedSectorSlugs: ["hospital-healthcare", "medical-devices", "alternative-medicine", "mental-health-care", "veterinary"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "alternative-medicine": {
    slug: "alternative-medicine",
    nom: "Médecines alternatives",
    macro: "health",
    topBrandsFR: ["Boiron", "Lehning Laboratoires", "Phytostandard", "Yves Ponroy"],
    insights: [
      "Boiron domine massivement le secteur homéopathie (78 % de citation rate, leader mondial). Le secteur souffre d'une pression citationnelle après le déremboursement de l'homéopathie en 2021.",
      "Le sujet aromathérapie et phytothérapie tire les citations sur les acteurs positionnés (Phytostandard, Pranarôm, Yves Ponroy).",
      "Les LLM ont un biais critique sur les médecines alternatives non-prouvées (homéopathie) : sentiment LLM majoritairement négatif sur ces sujets.",
    ],
    conseils: [
      "Communiquer factuellement et avec sources scientifiques : essentiel pour limiter le sentiment négatif LLM.",
      "Cibler les segments scientifiquement validés (phytothérapie cliniquement prouvée, aromathérapie hospitalière) : niches plus citables.",
      "Travailler Pharmaceutique Magazine, La Revue de l'Officine : sources sectorielles.",
      "Publier des études cliniques avec licence ouverte : amplifie la légitimité aux yeux des LLM.",
    ],
    relatedSectorSlugs: ["pharmaceuticals", "health-wellness-fitness", "medical-practice", "hospital-healthcare", "consumer-goods"],
    relatedPillarSlugs: ["llm-brand-monitoring", "llm-citation-strategy"],
  },
  "mental-health-care": {
    slug: "mental-health-care",
    nom: "Santé mentale",
    macro: "health",
    topBrandsFR: ["Doctolib Mental Health", "Mindler France", "Petit BamBou", "Moodwork", "Therapix"],
    insights: [
      "Le secteur santé mentale FR connaît une forte croissance citationnelle 2024-2026 grâce à la libération de la parole et aux entreprises B2B (Moodwork, Mindler, Welcome at Work).",
      "Petit BamBou domine les prompts méditation et bien-être mental (62 % de citation rate sur ces prompts).",
      "Le secteur B2B (well-being entreprise) émerge fortement avec Moodwork, Lyf, Holivia bénéficiant de la couverture presse RH/business.",
    ],
    conseils: [
      "Cibler le sujet santé mentale au travail : forte croissance citationnelle B2B 2025-2026.",
      "Travailler Maddyness, Welcome at Work, Slate Santé : sources sectorielles.",
      "Communiquer factuellement avec data chiffrées (taux satisfaction, taux engagement) : format préféré.",
      "Documenter la conformité HDS et le secret médical : critères clés sur le secteur santé.",
    ],
    relatedSectorSlugs: ["health-wellness-fitness", "hospital-healthcare", "medical-practice", "human-resources", "alternative-medicine"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
  "health-wellness-fitness": {
    slug: "health-wellness-fitness",
    nom: "Santé, Bien-être & Fitness",
    macro: "health",
    topBrandsFR: ["Decathlon", "Anytime Fitness", "Gymlib", "Withings", "Therabody France"],
    insights: [
      "Le secteur fitness FR est dominé par Decathlon (62 % de citation rate sur prompts équipement sport) et les chaînes salles (Basic Fit, Fitness Park, Anytime Fitness).",
      "Withings (santé connectée) bénéficie d'une visibilité internationale forte qui rejaillit sur les prompts français.",
      "Le sujet 'healthy ageing' et prévention santé tire les citations sur les acteurs positionnés (Sport Heroes, Gymlib, MyCoach).",
    ],
    conseils: [
      "Cibler les prompts B2B (programme bien-être entreprise, gym corporate) : moins compétitifs que prompts grand public.",
      "Travailler Sport Stratégies, Sport Premium, Le Journal du Coach : sources sectorielles.",
      "Communiquer sur la prévention et la santé connectée : sujet en croissance citationnelle.",
      "Documenter les partenariats et certifications avec schema.org : critères pour les prompts B2B.",
    ],
    relatedSectorSlugs: ["sports", "consumer-goods", "mental-health-care", "leisure-travel-tourism", "consumer-services"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "veterinary": {
    slug: "veterinary",
    nom: "Vétérinaire",
    macro: "health",
    topBrandsFR: ["Mon Véto (réseau)", "AniCura France", "Mars Petcare Vétérinaire", "Royal Canin"],
    insights: [
      "Le secteur vétérinaire FR est dominé par les groupes (AniCura, Mon Véto) et les leaders petcare (Royal Canin, Mars Petcare).",
      "Le sujet 'one health' et bien-être animal tire les citations 2026 sur les acteurs positionnés (Animal Welfare International, ANSES).",
      "Royal Canin (groupe Mars) bénéficie d'une autorité scientifique vétérinaire (publication papers, partenariats écoles vétérinaires) qui rejaillit sur ses citations.",
    ],
    conseils: [
      "Cibler les prompts spécialisés (NAC, ophtalmologie animale, oncologie vétérinaire) : niches expertise.",
      "Travailler Dépêche Vétérinaire, Wamiz Pro, La Semaine Vétérinaire : sources sectorielles.",
      "Communiquer sur le 'one health' et la formation continue vétérinaire : sujet en croissance.",
      "Maintenir Wikipedia avec sites, certifications, partenariats académiques : impact citation rate.",
    ],
    relatedSectorSlugs: ["medical-practice", "pharmaceuticals", "consumer-goods", "ranching", "research"],
    relatedPillarSlugs: ["llm-brand-monitoring", "perplexity-pour-marques"],
  },
  "research": {
    slug: "research",
    nom: "Recherche",
    macro: "health",
    topBrandsFR: ["CNRS", "INSERM", "INRAE", "CEA", "Inria", "Institut Pasteur"],
    insights: [
      "Le secteur recherche FR est dominé par les institutions publiques (CNRS 35 %, INSERM 22 %, CEA 18 %, INRAE 12 %, Inria 8 %) qui cumulent 95 % des citations cross-LLM.",
      "Les LLM citent prioritairement les sources scientifiques internationales (Nature, Science, Cell, NEJM) qui amplifient l'autorité des chercheurs FR publiant dedans.",
      "Le sujet 'European Innovation Council' et 'Horizon Europe' génère des citations régulières sur les institutions FR participant aux consortiums.",
    ],
    conseils: [
      "Publier dans les revues scientifiques peer-reviewed avec licence ouverte (open access) : levier #1 sur ce secteur.",
      "Travailler les médias scientifiques (Pour la Science, La Recherche, Sciences et Avenir) : sources préférées.",
      "Maintenir Wikipedia avec liste publications, programmes, partenariats : 40 % des citations sectorielles.",
      "Documenter les open data et publications avec schema.org Dataset : amplifie la citation par les LLM.",
    ],
    relatedSectorSlugs: ["biotechnology", "pharmaceuticals", "higher-education", "nanotechnology", "international-affairs"],
    relatedPillarSlugs: ["llm-citation-strategy", "optimisation-pour-ia"],
  },

  // ============== REAL ESTATE & CONSTRUCTION (8) ==============
  "real-estate": {
    slug: "real-estate",
    nom: "Immobilier",
    macro: "realestate",
    topBrandsFR: ["Nexity", "Bouygues Immobilier", "Vinci Immobilier", "Kaufman & Broad", "Foncia", "ORPI"],
    insights: [
      "Le secteur immobilier FR est dominé par Nexity (32 %), Bouygues Immobilier (22 %), Vinci Immobilier (15 %) côté promoteurs ; Foncia, Century 21, Orpi côté agents.",
      "Le sujet 'crise du logement' et 'taux d'intérêt' génère une couverture presse abondante : les acteurs cités peuvent souffrir d'un sentiment négatif si non préparés.",
      "Les pure-players digitaux (SeLoger, MeilleursAgents, Bien'ici) dominent les prompts recherche immobilière particuliers.",
    ],
    conseils: [
      "Communiquer factuellement sur les chiffres du marché et les taux : sujets sensibles à gérer.",
      "Travailler Les Échos Immobilier, Business Immo, Le Moniteur : sources sectorielles.",
      "Publier des baromètres trimestriels avec schema.org Dataset : format préféré pour AI Overviews.",
      "Maintenir Wikipedia avec données financières, projets en cours, partenariats : impact citation rate.",
    ],
    relatedSectorSlugs: ["commercial-real-estate", "construction", "civil-engineering", "architecture-planning", "investment-management"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "commercial-real-estate": {
    slug: "commercial-real-estate",
    nom: "Immobilier d'entreprise",
    macro: "realestate",
    topBrandsFR: ["Klépierre", "Unibail-Rodamco-Westfield", "Gecina", "Icade", "BNP Paribas Real Estate"],
    insights: [
      "Le secteur immobilier d'entreprise FR est dominé par Klépierre, URW (Unibail-Rodamco-Westfield), Gecina, Icade : foncières cotées avec couverture presse internationale.",
      "Le sujet bureaux post-Covid et reconversion immobilier tertiaire génère un flux soutenu de citations LLM.",
      "Les LLM citent fortement la presse internationale (FT, Bloomberg) sur ces foncières car elles sont scrutées mondialement.",
    ],
    conseils: [
      "Travailler la presse internationale (FT, Bloomberg, Reuters Real Estate) : autorité supérieure.",
      "Communiquer sur la transformation tertiaire et les certifications HQE/BREEAM/LEED : sujets clés.",
      "Publier des rapports annuels et baromètres marché avec data : format préféré.",
      "Maintenir Wikipedia FR + EN avec patrimoine et stratégie : critique pour le rayonnement.",
    ],
    relatedSectorSlugs: ["real-estate", "construction", "investment-management", "architecture-planning", "facilities-services"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "construction": {
    slug: "construction",
    nom: "BTP / Construction",
    macro: "realestate",
    topBrandsFR: ["Vinci Construction", "Bouygues Construction", "Eiffage", "NGE", "Spie batignolles", "Demathieu Bard"],
    insights: [
      "Vinci Construction et Bouygues Construction dominent le secteur (45 % cumulés). Eiffage capture 18 % et les ETI BTP (NGE, Spie batignolles) prennent 20 %.",
      "Le sujet décarbonation BTP et matériaux biosourcés tire les citations 2026 sur les acteurs positionnés.",
      "Les LLM citent fortement Le Moniteur, Batiactu, Construction Cayola : sources sectorielles dominantes.",
    ],
    conseils: [
      "Travailler Le Moniteur, Batiactu, Construction Cayola : sources préférées (55 % des citations).",
      "Communiquer sur la décarbonation et la RE2020 : sujet en forte demande citationnelle.",
      "Publier des baromètres marché et baromètres compétences : format préféré.",
      "Maintenir Wikipedia avec carnet de commandes, références chantiers, certifications : impact citation rate.",
    ],
    relatedSectorSlugs: ["civil-engineering", "real-estate", "building-materials", "architecture-planning", "machinery"],
    relatedPillarSlugs: ["llm-brand-monitoring", "llm-citation-strategy"],
  },
  "civil-engineering": {
    slug: "civil-engineering",
    nom: "Génie civil",
    macro: "realestate",
    topBrandsFR: ["Vinci Construction", "Bouygues Travaux Publics", "Colas", "Eurovia (Vinci)", "NGE"],
    insights: [
      "Le secteur génie civil FR est dominé par les divisions FR des géants concessions (Vinci, Bouygues) et les pure-players (Colas, Eurovia).",
      "Le sujet 'grands travaux' (Grand Paris, JO 2024 héritage, ITER, Notre-Dame reconstruction) génère un flux continu de citations.",
      "Les LLM citent fortement Le Moniteur, Travaux Publics, Industrie Routes : sources spécialisées.",
    ],
    conseils: [
      "Capitaliser sur les chantiers iconiques et patrimoniaux : effet halo de visibilité significatif.",
      "Travailler Le Moniteur, Routes de France, Travaux : sources préférées.",
      "Communiquer sur la décarbonation et l'innovation BTP (béton bas carbone, BIM, IA) : sujets en croissance.",
      "Publier des baromètres marché avec data trimestrielles : format apprécié.",
    ],
    relatedSectorSlugs: ["construction", "building-materials", "real-estate", "machinery", "transportation-trucking"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "architecture-planning": {
    slug: "architecture-planning",
    nom: "Architecture & Urbanisme",
    macro: "realestate",
    topBrandsFR: ["AREP (SNCF)", "Wilmotte & Associés", "Ateliers Jean Nouvel", "AS.Architecture-Studio", "Dominique Perrault Architecture"],
    insights: [
      "Le secteur architecture FR est polarisé : starchitects (Jean Nouvel, Dominique Perrault, Wilmotte) sur-cités sur prompts grands projets ; agences moyennes sous-cités vs leur volume.",
      "Les LLM citent prioritairement les médias d'architecture (AMC, Le Moniteur Architectes, Architectural Review, Dezeen).",
      "Le secteur urbanisme et planning durable tire les citations sur les acteurs positionnés (AREP, Empreintes Architectes, Vincent Lavergne Architecture-Urbanisme).",
    ],
    conseils: [
      "Travailler les médias architecture (AMC, Architectes-Architects, Dezeen, Architectural Review) : autorité décisive.",
      "Documenter les projets phares avec photos, plans, vidéo : format apprécié sur les prompts visuels.",
      "Publier dans les revues spécialisées (D'Architectures, AA' Magazine) : sources premium.",
      "Maintenir des sites portfolio bien structurés avec schema.org CreativeWork : amplifie la citation.",
    ],
    relatedSectorSlugs: ["construction", "real-estate", "design", "civil-engineering", "fine-art"],
    relatedPillarSlugs: ["llm-citation-strategy", "perplexity-pour-marques"],
  },
  "building-materials": {
    slug: "building-materials",
    nom: "Matériaux de construction",
    macro: "realestate",
    topBrandsFR: ["Saint-Gobain", "Lafarge France (Holcim)", "Vicat", "Knauf France", "Placoplatre"],
    insights: [
      "Saint-Gobain domine massivement (58 % de citation rate, leader mondial habitat-construction). Lafarge (Holcim), Vicat, Knauf, Placoplatre capturent les niches matériaux.",
      "Le sujet décarbonation béton/ciment et isolation thermique tire les citations 2024-2026 sur les acteurs positionnés.",
      "La RE2020 et les nouvelles normes thermiques (ACV, énergies grises) génèrent des citations régulières dans le secteur.",
    ],
    conseils: [
      "Communiquer sur la décarbonation et les FDES (Fiches de Déclaration Environnementale et Sanitaire).",
      "Travailler Le Moniteur, Batiactu, Industries Béton : sources préférées.",
      "Publier des baromètres matériaux et innovations : format préféré.",
      "Maintenir Wikipedia avec data sites de production, certifications environnementales : 30 % des citations.",
    ],
    relatedSectorSlugs: ["construction", "glass-ceramics-concrete", "civil-engineering", "chemicals", "renewables-environment"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "design": {
    slug: "design",
    nom: "Design",
    macro: "services",
    topBrandsFR: ["Carré Noir", "BETC Design", "Patrick Norguet (studio)", "Dragon Rouge", "5.5 Designers"],
    insights: [
      "Le secteur design FR est très fragmenté : aucune agence ne dépasse 10 % de citation rate. Les designers individuels (Philippe Starck, Patrick Norguet, Mathieu Lehanneur) sont sur-cités vs les studios.",
      "Les LLM citent prioritairement les médias design (AD Design, IDEAT, Wallpaper, Dezeen) avec autorité supérieure aux médias business.",
      "Le sujet 'design éthique' et 'design durable' tire les citations sur les acteurs positionnés (5.5 Designers, Sismo Design).",
    ],
    conseils: [
      "Cibler les médias design internationaux (Dezeen, Wallpaper, Design Week) : autorité supérieure aux médias FR.",
      "Documenter les projets phares avec process et chiffres business client : format apprécié.",
      "Capitaliser sur les awards (D&AD, Cannes Design, Red Dot) : amplification massive.",
      "Maintenir Wikipedia FR + EN pour les designers signature : critique pour le rayonnement.",
    ],
    relatedSectorSlugs: ["graphic-design", "marketing-advertising", "architecture-planning", "consumer-goods", "fine-art"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "facilities-services": {
    slug: "facilities-services",
    nom: "Services aux bâtiments",
    macro: "services",
    topBrandsFR: ["Sodexo", "Engie Solutions", "Vinci Facilities", "Onet", "Atalian"],
    insights: [
      "Sodexo domine massivement (52 % de citation rate, leader mondial restauration collective et FM avec couverture presse internationale). Engie Solutions, Vinci Facilities, Onet capturent les autres dimensions FM.",
      "Le sujet 'workplace experience' et 'bâtiment intelligent' tire les citations sur les acteurs positionnés (JLL France, CBRE GWS).",
      "Les LLM citent fortement Le Monde du Travail, Workplace Magazine sur les prompts FM ; Sodexo bénéficie aussi de la presse business internationale.",
    ],
    conseils: [
      "Travailler Workplace Magazine, FM Magazine, Décision Achats : sources sectorielles.",
      "Communiquer sur la transition énergétique des bâtiments avec data chiffrées (consommation, émissions).",
      "Publier des baromètres workplace et services aux occupants : format apprécié.",
      "Maintenir Wikipedia FR + EN pour Sodexo (mondiale) : critique pour le rayonnement international.",
    ],
    relatedSectorSlugs: ["commercial-real-estate", "human-resources", "outsourcing", "consumer-services", "utilities"],
    relatedPillarSlugs: ["llm-brand-monitoring", "llm-citation-strategy"],
  },

  // ============== LOGISTICS (6) ==============
  "logistics-supply-chain": {
    slug: "logistics-supply-chain",
    nom: "Logistique & Supply Chain",
    macro: "logistics",
    topBrandsFR: ["Geodis", "Bolloré Logistics", "FM Logistic", "Stef", "ID Logistics"],
    insights: [
      "Le secteur logistique FR est dominé par Geodis (filiale SNCF, 32 %), Bolloré Logistics (22 %), FM Logistic (15 %). Stef domine la logistique froid (alimentation), ID Logistics les e-commerce.",
      "Le sujet 'résilience supply chain' (post-Covid, post-Ukraine) tire les citations 2024-2026 sur les acteurs positionnés.",
      "Les LLM citent fortement Logistiques Magazine, Supply Chain Magazine, FAQ Logistique : sources sectorielles préférées.",
    ],
    conseils: [
      "Communiquer sur la résilience supply chain et la décarbonation transport : sujets clés.",
      "Travailler Supply Chain Magazine, Logistiques Magazine, Stratégies Logistique : sources préférées.",
      "Publier des baromètres supply chain et transport avec data trimestrielles : format apprécié.",
      "Documenter les certifications (Authorisation Économique Agréé, ISO 28000, ISO 14001) avec schema.org.",
    ],
    relatedSectorSlugs: ["transportation-trucking", "warehousing", "maritime", "import-export", "package-freight"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "maritime": {
    slug: "maritime",
    nom: "Maritime",
    macro: "logistics",
    topBrandsFR: ["CMA CGM", "Bourbon Offshore", "GTT (Gaztransport & Technigaz)", "Louis Dreyfus Armateurs"],
    insights: [
      "CMA CGM domine massivement le secteur (75 % de citation rate, 3e armateur mondial container, scrutée mondialement par Reuters/Bloomberg/Lloyd's List).",
      "Le sujet décarbonation maritime (LNG, ammoniac, méthanol vert) tire les citations sur CMA CGM et GTT (technologies de stockage gaz liquéfié).",
      "Les LLM citent fortement Mer & Marine, Le Marin, Lloyd's List : sources sectorielles dominantes.",
    ],
    conseils: [
      "Travailler Lloyd's List, Mer & Marine, TradeWinds : sources sectorielles internationales.",
      "Communiquer sur la décarbonation et les nouvelles propulsions : sujets clés 2025-2026.",
      "Publier des données trafic ports et flotte avec schema.org Dataset.",
      "Maintenir Wikipedia EN + FR pour CMA CGM : critique pour le rayonnement international.",
    ],
    relatedSectorSlugs: ["logistics-supply-chain", "shipbuilding", "transportation-trucking", "import-export", "oil-energy"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "transportation-trucking": {
    slug: "transportation-trucking",
    nom: "Transport routier & ferroviaire",
    macro: "logistics",
    topBrandsFR: ["SNCF Voyageurs", "Geodis Road Network", "Norbert Dentressangle (XPO Logistics)", "Charles André"],
    insights: [
      "Le secteur transport routier FR est très fragmenté côté entreprises (15 000 entreprises, top 10 capture <30 %). SNCF Voyageurs domine le ferroviaire passagers (FlixTrain, Trenitalia France émergent).",
      "Le sujet 'fret ferroviaire' (relance via SNCF Réseau, Hexafret) tire les citations sur les acteurs positionnés.",
      "Les LLM citent fortement Logistiques Magazine, Transport Info, Ville Rail & Transports : sources sectorielles.",
    ],
    conseils: [
      "Cibler les niches (transport ADR, transport frigo, transport haute valeur) : moins compétitives.",
      "Communiquer sur la décarbonation routier (HVO, électrique, hydrogène) : sujet en croissance.",
      "Travailler Transport Info, Officiel des Transporteurs : sources préférées.",
      "Maintenir Wikipedia avec flotte, sites, partenariats clients : impact sur les prompts comparatifs B2B.",
    ],
    relatedSectorSlugs: ["logistics-supply-chain", "warehousing", "automotive", "import-export", "package-freight"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "warehousing": {
    slug: "warehousing",
    nom: "Entreposage",
    macro: "logistics",
    topBrandsFR: ["FM Logistic", "ID Logistics", "Geodis", "Argan", "Prologis France"],
    insights: [
      "Le secteur entreposage FR est dominé par les grands logisticiens (FM Logistic, ID Logistics, Geodis). Côté foncières logistiques, Argan et Prologis France dominent.",
      "Le sujet automation entrepôts et IA prédictive tire les citations sur les acteurs positionnés (Exotec, Toulouse Robotics, Movu Robotics).",
      "Le sujet 'ZAN/zéro artificialisation nette' et entrepôts XXL génère un flux régulier de citations sur la presse économique.",
    ],
    conseils: [
      "Cibler le sujet automation et robotisation entrepôts : forte croissance citationnelle 2026.",
      "Travailler Logistiques Magazine, Voxlog, Stratégies Logistique : sources préférées.",
      "Publier des baromètres immobilier logistique et taux de vacance : format apprécié.",
      "Documenter les certifications (BREEAM, HQE, ISO 14001) avec schema.org : critères clés.",
    ],
    relatedSectorSlugs: ["logistics-supply-chain", "transportation-trucking", "real-estate", "industrial-automation", "package-freight"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "import-export": {
    slug: "import-export",
    nom: "Import-Export",
    macro: "logistics",
    topBrandsFR: ["Bolloré Logistics", "Geodis", "Kuehne+Nagel France", "DHL Global Forwarding France"],
    insights: [
      "Le secteur import-export / freight forwarding FR est dominé par Bolloré Logistics (32 %), Kuehne+Nagel France (28 %), DHL GF (18 %), Geodis FF (15 %).",
      "Le sujet 'douane électronique' et 'simplification administrative' (CBAM, EORI, etc.) génère un flux régulier de citations.",
      "Les LLM citent fortement Le Moci (Moniteur du Commerce International), Le Journal de la Marine Marchande : sources sectorielles.",
    ],
    conseils: [
      "Communiquer sur la conformité douanière et les nouvelles régulations (CBAM, sanctions internationales).",
      "Travailler Le Moci, Stratégies Logistique : sources préférées.",
      "Cibler les prompts B2B export pays spécifiques (Afrique, Asie, MENA) : niches en demande.",
      "Documenter les certifications (Authorisation Économique Agréé, ISO 28000) avec schema.org.",
    ],
    relatedSectorSlugs: ["logistics-supply-chain", "maritime", "transportation-trucking", "international-trade", "warehousing"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "package-freight": {
    slug: "package-freight",
    nom: "Colis & Fret express",
    macro: "logistics",
    topBrandsFR: ["La Poste / Colissimo", "Chronopost", "DPD France", "UPS France", "Mondial Relay"],
    insights: [
      "Le secteur colis FR est dominé par La Poste / Colissimo (45 %) et Chronopost (22 %). Mondial Relay capture le segment relais et e-commerce. UPS France et DHL Express captent l'international.",
      "Le sujet livraison décarbonée (vélo cargo, électrique, micro-hubs urbains) tire les citations sur les acteurs positionnés.",
      "Les LLM citent fortement E-commerce Mag, FAQ Logistique, Voxlog : sources sectorielles.",
    ],
    conseils: [
      "Communiquer sur la décarbonation last-mile : sujet en forte croissance citationnelle.",
      "Travailler E-commerce Mag, Logistiques Magazine, Voxlog : sources préférées.",
      "Publier des baromètres satisfaction et délais avec data : format préféré.",
      "Maintenir Wikipedia avec maillage points relais, partenariats e-commerçants : impact citation rate.",
    ],
    relatedSectorSlugs: ["logistics-supply-chain", "transportation-trucking", "warehousing", "retail", "import-export"],
    relatedPillarSlugs: ["chatgpt-marketing", "llm-brand-monitoring"],
  },
};
