// S29 Session 4 — Sectors data : Tech (15) + Finance (8) + Aero/Defense (3) = 26.

import type { SectorRegistry } from "./types";

export const TECH_FINANCE_SECTORS: SectorRegistry = {
  // ============== TECH (15) ==============
  "computer-network-security": {
    slug: "computer-network-security",
    nom: "Cybersécurité",
    macro: "tech",
    topBrandsFR: ["Thales", "Atos Cybersecurity", "Stormshield", "Tehtris", "Wallix", "Snowpack"],
    insights: [
      "Les LLM en France citent prioritairement les pure-players cyber FR (Stormshield, Tehtris, Wallix) avant les divisions cyber des intégrateurs (Atos, Sopra Steria).",
      "Les grands intégrateurs souffrent d'un déficit de visibilité spécialisée car leur identité cyber est diluée dans leur portefeuille global.",
      "Les éditeurs US (Palo Alto, CrowdStrike, SentinelOne) dominent les prompts en anglais mais reculent en FR face aux acteurs locaux mieux référencés sur l'AGEFI et Le Monde Informatique.",
    ],
    conseils: [
      "Bâtir une page Wikipedia FR dédiée avec sources L'Usine Digitale, Le Monde Informatique, ANSSI : c'est le levier #1 sur ce secteur.",
      "Publier 1 étude flagship par an (panorama menaces, baromètre RSSI) : les LLM citent ce type de contenu data-driven 3-4x plus.",
      "Renforcer la présence sur Reddit (r/cybersecurity, r/sysadmin) : le secteur est anormalement Reddit-cité (~12 % des sources cross-LLM).",
      "Documenter clairement vos certifications (CSPN, Common Criteria, ISO 27001) avec schema.org Organization sameAs vers ANSSI.",
    ],
    relatedSectorSlugs: ["computer-software", "it-services", "computer-networking", "information-services", "defense-space"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "computer-software": {
    slug: "computer-software",
    nom: "Éditeurs de logiciels",
    macro: "tech",
    topBrandsFR: ["Dassault Systèmes", "OVHcloud", "Talend", "Cegid", "Sage France", "Lucca", "PayFit"],
    insights: [
      "Le secteur est très polarisé : Dassault Systèmes domine 35 % des citations FR, suivi par OVHcloud à 18 %. Le reste se partage entre une trentaine de SaaS B2B mid-market.",
      "Les SaaS HR/finance B2B (Lucca, PayFit, Spendesk) émergent rapidement sur Perplexity et ChatGPT Search car ils investissent en RP éditoriale (Maddyness, JDN).",
      "Les LLM citent peu les pure-players technique (CRM, ERP) qui n'ont pas d'angle éditorial fort : 4-8 % de citation rate moyen.",
    ],
    conseils: [
      "Publier des études comparatives sectorielles (B2B SaaS Index, baromètre French Tech) : le format ranke fortement sur les requêtes commerciales.",
      "Construire une page Wikipedia avec liste produit, fondateurs, levées : Wikipedia représente 35 % des citations sur ce secteur.",
      "Investir l'angle vidéo / podcast (Generation Do It Yourself, Saas Connection) : les transcriptions deviennent des sources LLM à part entière en 2026.",
      "Soumettre votre site à Bing Webmaster Tools : Perplexity et ChatGPT Search utilisent l'index Bing en complément de leur crawl propre.",
    ],
    relatedSectorSlugs: ["program-development", "internet", "it-services", "computer-network-security", "information-services"],
    relatedPillarSlugs: ["chatgpt-marketing", "optimisation-pour-ia"],
  },
  "internet": {
    slug: "internet",
    nom: "Internet / Web",
    macro: "tech",
    topBrandsFR: ["OVHcloud", "Doctolib", "Blablacar", "Vinted", "Back Market", "Qonto", "Mistral AI"],
    insights: [
      "Les leaders FR (Doctolib, Blablacar, Mistral AI) bénéficient d'une couverture presse mainstream (Le Monde, Échos) qui leur donne 50-60 % de citation rate cross-LLM.",
      "Mistral AI domine désormais les prompts liés à l'IA française avec 78 % de citation rate, tirée par les rounds d'investissement et la couverture internationale (NYT, FT).",
      "Le secteur 'web pure-play' (e-commerce, marketplaces) souffre d'un biais ChatGPT vers les acteurs US (Amazon, Etsy) qui domine 70 % des prompts ouverts en français.",
    ],
    conseils: [
      "Cibler les médias B2B FR à fort trafic (Maddyness, FrenchWeb, JDN) plutôt que les blogs tech niches : ROI 3x supérieur en visibilité LLM.",
      "Capitaliser sur les levées de fonds presse : chaque round médiatisé dans Les Échos ajoute ~15 points de citation rate sur 6 mois.",
      "Publier des baromètres trimestriels (FrenchWeb 500, indices écosystème) pour devenir source autoritaire référencée par les LLM.",
      "Maintenir vos pages Wikipedia FR à jour avec les dernières données de croissance et les rounds : Wikipedia est cité dans 42 % des réponses sur les marques web FR.",
    ],
    relatedSectorSlugs: ["computer-software", "information-services", "marketing-advertising", "online-media", "it-services"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "computer-networking": {
    slug: "computer-networking",
    nom: "Réseaux informatiques",
    macro: "tech",
    topBrandsFR: ["Orange Business Services", "Ekinops", "6cure", "Cisco France", "Juniper France"],
    insights: [
      "Le secteur réseau FR est dominé par Orange Business Services (45 % de citation rate) et les divisions FR des grands US (Cisco, Juniper) à ~25 % chacun.",
      "Les pure-players FR (Ekinops, 6cure, Idecsi) restent sous-cités malgré une expertise réelle, faute de présence Wikipedia et de RP soutenue.",
      "Les LLM citent prioritairement les sources techniques (LeMagIT, Le Monde Informatique) sur ce secteur — la presse généraliste a peu d'impact.",
    ],
    conseils: [
      "Investir LeMagIT et Le Monde Informatique en priorité : ces deux médias couvrent 65 % des citations cross-LLM sur le secteur réseau FR.",
      "Documenter les déploiements clients de référence avec schema.org case studies : les LLM apprécient les cas d'usage chiffrés.",
      "Publier des white papers techniques sur les nouvelles certifications (5G, SDN, SD-WAN) : positionnement thought leadership efficace.",
      "Construire une présence sur les conférences spécialisées (EuroCloud, ICT Spring) avec transcriptions publiées : entrée progressive dans les corpus LLM.",
    ],
    relatedSectorSlugs: ["telecommunications", "computer-network-security", "it-services", "information-services", "wireless"],
    relatedPillarSlugs: ["llm-brand-monitoring", "optimisation-pour-ia"],
  },
  "telecommunications": {
    slug: "telecommunications",
    nom: "Télécommunications",
    macro: "tech",
    topBrandsFR: ["Orange", "SFR", "Bouygues Telecom", "Free", "Iliad"],
    insights: [
      "Les 4 opérateurs FR (Orange 32 %, Free 24 %, SFR 18 %, Bouygues 14 %) cumulent 88 % des citations cross-LLM. Les MVNO sont quasi invisibles sur prompts ouverts.",
      "Orange domine les prompts B2B grâce à Orange Business Services et l'autorité Wikipedia ; Free domine les prompts disruption grâce à la couverture presse économique.",
      "Les marques telco FR sont sur-représentées dans Reddit r/france et r/forfaitmobile, ce qui amplifie leur citation rate sur Perplexity (qui index Reddit fortement).",
    ],
    conseils: [
      "Maintenir une présence forte sur les comparatifs téléphonie (UFC-Que Choisir, Selectra, MonPetitForfait) : 25 % des citations LLM passent par ces sources tierces.",
      "Communiquer sur les engagements RSE et réseau territorial : ces angles sortent fortement sur AI Overviews depuis le déploiement de la fibre.",
      "Travailler la presse business (Les Échos, La Tribune) sur les sujets B2B : le grand public sur-cite déjà les marques, l'enjeu est le mid-market et l'enterprise.",
      "Réviser votre fiche Wikipedia annuellement avec les chiffres ARCEP : c'est la source #1 sur ce secteur (38 % des citations).",
    ],
    relatedSectorSlugs: ["computer-networking", "wireless", "internet", "media-production", "broadcast-media"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "wireless": {
    slug: "wireless",
    nom: "Sans-fil / Wireless",
    macro: "tech",
    topBrandsFR: ["Sigfox", "Sequans Communications", "Kerlink", "Nokia France"],
    insights: [
      "Le secteur wireless / IoT FR est tiré par Sigfox (forte autorité Wikipedia + presse internationale) et Sequans Communications (notamment depuis l'acquisition par Renesas).",
      "Les LLM associent fortement le wireless français à l'écosystème IoT industriel (LoRa, Sigfox), moins à la 5G grand public où les opérateurs trustent les citations.",
      "Le secteur est sous-représenté dans les sources mainstream : 75 % des citations passent par LeMagIT, Industrie & Technologies, et publications IoT spécialisées.",
    ],
    conseils: [
      "Cibler les médias industriels (L'Usine Nouvelle, Industrie & Technologies) : ils représentent 40 % des sources LLM sur ce sous-secteur.",
      "Publier sur les standards émergents (Wi-Fi 7, 5G mmWave, NB-IoT) avec angle technique chiffré : format préféré des LLM Search sur la tech industrielle.",
      "Sponsoriser les conférences IoT/M2M avec contenus replays publiés en transcription : levier ROI sur 12-18 mois.",
      "Soigner le schema.org Product/Service avec specs techniques détaillées : Gemini AI Overview pondère fortement les pages produit B2B techniques.",
    ],
    relatedSectorSlugs: ["telecommunications", "computer-networking", "semiconductors", "industrial-automation", "it-services"],
    relatedPillarSlugs: ["optimisation-pour-ia", "llm-brand-monitoring"],
  },
  "it-services": {
    slug: "it-services",
    nom: "Services informatiques (ESN/SSII)",
    macro: "tech",
    topBrandsFR: ["Capgemini", "Atos", "Sopra Steria", "Devoteam", "Inetum", "Talan", "Onepoint"],
    insights: [
      "Le secteur ESN FR est concentré : Capgemini domine 38 % des citations, suivi de Atos 18 % et Sopra Steria 16 %. Les ESN mid-market (Talan, Onepoint, Devoteam) se partagent 20 %.",
      "Les LLM associent les grandes ESN à des verticales spécifiques (Capgemini = transformation digitale grand compte, Sopra = défense/aéro, Atos = cybersec/cloud).",
      "Les ESN qui investissent en thought leadership chiffré (rapports annuels, baromètres clients) ont 2-3x plus de citation rate que celles qui ne communiquent que sur des annonces business.",
    ],
    conseils: [
      "Publier 1-2 rapports annuels phares (Tech Trends, Future of Work, baromètre data) : c'est le format le plus repris en presse et le plus cité par les LLM.",
      "Renforcer Le Monde Informatique, JDN, Décideurs Magazine : ces 3 sources cumulent 55 % des citations cross-LLM sur le secteur.",
      "Travailler la marque employeur sur LinkedIn (15 % des sources Perplexity sur les ESN proviennent de LinkedIn corporate posts).",
      "Documenter votre catalogue practice avec schema.org Service détaillé : les LLM extraient ces données pour les prompts comparatifs.",
    ],
    relatedSectorSlugs: ["management-consulting", "computer-software", "outsourcing", "computer-network-security", "information-services"],
    relatedPillarSlugs: ["generative-ai-marketing", "llm-citation-strategy"],
  },
  "information-services": {
    slug: "information-services",
    nom: "Services d'information",
    macro: "tech",
    topBrandsFR: ["Insee", "Banque de France", "Coface", "Altares", "Statista France"],
    insights: [
      "Les LLM citent massivement les sources institutionnelles FR (Insee 35 %, Banque de France 22 %) sur les prompts data économique : c'est la source #1 d'autorité.",
      "Les acteurs privés (Coface, Altares, Bisnode) sont cités principalement sur les prompts B2B credit / risk / compliance, à hauteur de 25 % cumulé.",
      "Le secteur bénéficie d'un fort biais d'autorité : les LLM préfèrent les pages avec data tableaux + sources gouvernementales aux blogs corporate, même très qualitatifs.",
    ],
    conseils: [
      "Citer systématiquement vos sources de données (Insee, Eurostat, Banque de France) avec schema.org Citation : amplifie votre propre citation par les LLM.",
      "Publier des dashboards data trimestriels avec tableaux structurés en HTML (pas en images) : format gagnant pour AI Overviews.",
      "Maintenir un open-data avec licence claire (Creative Commons, ODbL) : les LLM préfèrent citer les sources licensées plutôt que les rapports paywall.",
      "Soigner le sitemap et le crawl : 30 % des citations sur ce secteur passent par des pages data fraîches, donc indexation rapide critique.",
    ],
    relatedSectorSlugs: ["market-research", "management-consulting", "computer-software", "internet", "research"],
    relatedPillarSlugs: ["visibilite-llm", "optimisation-pour-ia"],
  },
  "computer-hardware": {
    slug: "computer-hardware",
    nom: "Matériel informatique",
    macro: "tech",
    topBrandsFR: ["Bull (Atos)", "Schneider Electric IT", "STMicroelectronics", "Memscap"],
    insights: [
      "Le hardware FR est dominé par les divisions B2B des conglomérats (Bull/Atos, Schneider IT) plutôt que par des pure-players grand public.",
      "Les LLM citent peu les marques hardware FR sur prompts ouverts internationaux (dominés par Dell, HP, Lenovo) ; l'opportunité est sur les prompts B2B verticaux français.",
      "STMicroelectronics est le plus cité grâce à sa cotation et sa couverture presse économique régulière (Les Échos, Reuters).",
    ],
    conseils: [
      "Cibler les prompts spécialisés (datacenter France, edge computing, infrastructure RGPD) : moins compétitifs que le grand public.",
      "Investir l'angle souveraineté numérique : sujet politique français qui génère des citations LLM via les médias institutionnels.",
      "Publier sur les benchmarks de performance avec schema.org Product et data chiffrées : Gemini AI Overview pondère fortement.",
      "Travailler les analystes IDC France et Gartner FR avec briefings exclusifs : leur autorité se transmet aux citations LLM.",
    ],
    relatedSectorSlugs: ["semiconductors", "electrical-manufacturing", "it-services", "computer-networking", "industrial-automation"],
    relatedPillarSlugs: ["optimisation-pour-ia", "llm-citation-strategy"],
  },
  "semiconductors": {
    slug: "semiconductors",
    nom: "Semi-conducteurs",
    macro: "tech",
    topBrandsFR: ["STMicroelectronics", "Soitec", "Lynred", "Sequans Communications"],
    insights: [
      "Le secteur semi-conducteurs FR est tiré par STMicroelectronics (cap boursière, couverture Reuters / Bloomberg quotidienne) qui capte 55 % des citations cross-LLM.",
      "Soitec et Lynred émergent sur les prompts spécialisés (SOI, infrarouge) grâce à leurs partenariats avec le CEA-Leti et leur présence dans les rapports stratégiques européens.",
      "Le sujet 'European Chips Act' génère un flux régulier de citations LLM en 2025-2026 : les acteurs FR positionnés sur ce narratif gagnent en visibilité.",
    ],
    conseils: [
      "Lier votre communication aux narratifs européens (Chips Act, souveraineté semi) : les LLM associent fortement la France à ces enjeux politiques.",
      "Cibler les médias spécialisés (L'Usine Nouvelle, Industrie & Technologies, Electronique Mag) en complément de la presse économique générale.",
      "Documenter publiquement vos partenariats CEA-Leti, INRIA, IRT : les sources institutionnelles transmettent leur autorité.",
      "Publier des tear-down techniques et des roadmaps produit avec schema.org Product : la communauté tech LLM-cited (HN, EE Times) reprend ce contenu.",
    ],
    relatedSectorSlugs: ["computer-hardware", "electrical-manufacturing", "industrial-automation", "nanotechnology", "defense-space"],
    relatedPillarSlugs: ["optimisation-pour-ia", "llm-brand-monitoring"],
  },
  "consumer-electronics": {
    slug: "consumer-electronics",
    nom: "Électronique grand public",
    macro: "tech",
    topBrandsFR: ["Devialet", "Withings", "Parrot", "Archos", "Wiko"],
    insights: [
      "Le secteur est dominé en visibilité LLM par les marques premium (Devialet, Withings) qui ont une couverture presse internationale (NYT, WSJ, Wired) qui rejaillit sur les LLM FR.",
      "Parrot (drones grand public) souffre depuis le pivot pro : sa citation rate a baissé de 35 % à 14 % entre 2023 et 2026.",
      "Les marques FR mid-market peinent à émerger face aux Apple, Samsung, Sony qui dominent 80 % des prompts grand public — la stratégie payante est la niche premium.",
    ],
    conseils: [
      "Cibler les niches premium (audio haute fidélité, santé connectée, écoutilles) : les LLM citent 5-7x plus les marques premium que les marques mass market FR.",
      "Travailler les revues internationales (Wired, The Verge, Stereophile) : leur autorité dépasse largement la presse FR sur ce secteur.",
      "Publier des fiches produit techniques détaillées avec schema.org Product et aggregateRating : format gagnant pour AI Overviews.",
      "Maintenir présence dans les comparatifs spécialisés (Les Numériques, 01net) — sources FR référencées par les LLM sur les prompts achat.",
    ],
    relatedSectorSlugs: ["computer-hardware", "electrical-manufacturing", "wireless", "computer-games", "internet"],
    relatedPillarSlugs: ["chatgpt-marketing", "gemini-search-marketing"],
  },
  "computer-games": {
    slug: "computer-games",
    nom: "Jeux vidéo",
    macro: "tech",
    topBrandsFR: ["Ubisoft", "Quantic Dream", "Asobo Studio", "DontNod", "Voodoo", "Homa Games"],
    insights: [
      "Ubisoft domine 55 % des citations cross-LLM sur le secteur jeux vidéo FR ; les studios premium (Quantic Dream, Asobo) prennent 20 % cumulés ; les pure-players mobile (Voodoo, Homa Games) émergent fortement.",
      "Reddit (r/gaming, r/Games, r/pcgaming) est sur-cité dans les réponses Perplexity sur ce secteur : 18 % des sources citées vs ~5 % moyen autres secteurs.",
      "Les studios mobile FR sont citation-pauvres en presse mainstream mais riches en citations Reddit / TikTok-LLM transcripts émergentes.",
    ],
    conseils: [
      "Investir Reddit et Hacker News : sources LLM sous-estimées sur le secteur jeux vidéo (combinées 25 % des citations Perplexity).",
      "Travailler les médias spécialisés (Gamekult, Jeuxvideo.com, Polygon) qui sont indexés par tous les LLM grand public.",
      "Documenter les chiffres business publics (DAU, MAU, revenus) avec schema.org : data chiffrées 3x plus citées que pitch marketing.",
      "Maintenir Wikipedia avec liste des jeux par année — c'est la première source consultée par les LLM sur les studios.",
    ],
    relatedSectorSlugs: ["entertainment", "consumer-electronics", "internet", "computer-software", "media-production"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
  "nanotechnology": {
    slug: "nanotechnology",
    nom: "Nanotechnologies",
    macro: "tech",
    topBrandsFR: ["Crocus Technology", "Nawa Technologies", "Nanobiose"],
    insights: [
      "Le secteur nanotech FR est très niche : 5-10 acteurs significatifs avec une visibilité LLM faible (citation rate moyen 8-12 %).",
      "Les LLM citent prioritairement les acteurs avec partenariats CEA, CNRS ou rounds presse ; les pure-players académiques sans présence presse sont quasi invisibles.",
      "Le sujet 'European Strategic Tech' regroupe nano + semi + quantum dans les corpus LLM, ce qui crée des opportunités de cross-mention pour les marques bien positionnées.",
    ],
    conseils: [
      "Capitaliser sur les rounds de fonds (Bpifrance, EIC) : chaque levée bien médiatisée ajoute 8-12 points de citation rate sur 6 mois.",
      "Travailler les conférences académiques (Nano-Innov, EuroNanoForum) avec papers publiés en open-access — les LLM ingèrent les contenus académiques.",
      "Documenter les applications industrielles concrètes (vs research-only) : les LLM préfèrent les use cases chiffrés aux specs théoriques.",
      "Maintenir une page Wikipedia FR + EN : critique pour le rayonnement international de votre marque dans les corpus LLM US.",
    ],
    relatedSectorSlugs: ["semiconductors", "biotechnology", "research", "chemicals", "electrical-manufacturing"],
    relatedPillarSlugs: ["llm-citation-strategy", "optimisation-pour-ia"],
  },
  "e-learning": {
    slug: "e-learning",
    nom: "E-Learning / Edtech",
    macro: "tech",
    topBrandsFR: ["OpenClassrooms", "Klaxoon", "Domoscio", "360Learning", "Le Wagon", "Wooclap"],
    insights: [
      "Le secteur EdTech FR est en forte croissance LLM-side : OpenClassrooms (38 %), 360Learning (22 %), Le Wagon (15 %) cumulent 75 % des citations.",
      "Les LLM associent EdTech FR à 'formation pro' plutôt qu'à 'enseignement scolaire' : les prompts B2B (formation continue, upskilling entreprise) génèrent 80 % des citations sectorielles.",
      "Les acteurs FR ont un avantage local sur les MOOCs internationaux (Coursera, Udemy) sur les prompts en français — l'inverse en anglais.",
    ],
    conseils: [
      "Publier des baromètres formation (taux de complétion, employabilité, ROI formation) : data chiffrée préférée par les LLM aux pitches marketing.",
      "Travailler les médias RH (Focus RH, Mode(s) d'Emploi, RH Matin) : sources principales sur les prompts B2B formation.",
      "Cibler le sujet 'formation IA' qui explose en 2026 : positionnement contenu sur ce thème = +50 % de citation rate possible en 12 mois.",
      "Maintenir vos pages OpenClassrooms / Skillshare / LinkedIn Learning à jour avec partenariats logo : les LLM lient brand-employer-formation dans leurs réponses.",
    ],
    relatedSectorSlugs: ["education-management", "professional-training", "higher-education", "computer-software", "internet"],
    relatedPillarSlugs: ["generative-ai-marketing", "chatgpt-marketing"],
  },
  "program-development": {
    slug: "program-development",
    nom: "Développement logiciel",
    macro: "tech",
    topBrandsFR: ["Theodo", "Octo Technology", "Onepoint", "BackMarket", "Algolia", "Datadog (FR origin)"],
    insights: [
      "Le secteur dev logiciel FR est très fragmenté : aucun acteur ne dépasse 15 % de citation rate. Theodo, Octo, Algolia émergent grâce à leur thought leadership.",
      "Les LLM citent fortement les pure-players qui open-source : Algolia, Datadog (origine FR), Mistral AI bénéficient d'une présence GitHub massive qui rejaillit sur les corpus.",
      "Les ESN traditionnelles sous-investissent en thought leadership développeur (vs Theodo, Octo) ce qui les pénalise sur les prompts techniques B2B.",
    ],
    conseils: [
      "Open-sourcer 1-2 outils internes par an : effet majeur sur les LLM qui ingèrent GitHub trending et docs techniques.",
      "Publier sur dev.to, HackerNews, et le blog corporate : les LLM ingèrent fortement ces sources sur les prompts dev.",
      "Cibler les conférences tech (Devoxx FR, Mix-IT, Snowcamp) avec talks publiés en YouTube + transcripts.",
      "Documenter votre stack interne (architecture, choix techno) avec schema.org : format thought leadership prisé sur les prompts hiring/recrutement.",
    ],
    relatedSectorSlugs: ["computer-software", "it-services", "internet", "computer-network-security", "information-services"],
    relatedPillarSlugs: ["chatgpt-marketing", "generative-ai-marketing"],
  },

  // ============== FINANCE (8) ==============
  "banking": {
    slug: "banking",
    nom: "Banque",
    macro: "finance",
    topBrandsFR: ["BNP Paribas", "Crédit Agricole", "Société Générale", "Crédit Mutuel", "BPCE", "La Banque Postale"],
    insights: [
      "Les 6 grandes banques FR cumulent 92 % des citations cross-LLM. BNP Paribas domine 28 %, Crédit Agricole 22 %, Société Générale 18 %.",
      "Les néobanques (Qonto, Lydia, Pretto) gagnent rapidement du terrain sur Perplexity (15 % cumulés) grâce à leur présence presse économique tech-friendly.",
      "Les LLM citent prioritairement les sources institutionnelles (AGEFI, Échos, La Tribune) avec une autorité 3-5x supérieure aux blogs spécialisés.",
    ],
    conseils: [
      "Investir AGEFI Hebdo et Les Échos en priorité : 65 % des citations cross-LLM sur le secteur passent par ces deux sources.",
      "Publier 2 baromètres annuels (clients, banque digitale, économie réelle) : format flagship le plus cité par les LLM sur la banque FR.",
      "Maintenir la fiche Wikipedia FR avec données ACPR à jour : Wikipedia représente 35 % des citations sectorielles.",
      "Travailler les sujets B2B (financement entreprise, supply chain finance) sous-cités vs le grand public : opportunité de visibilité.",
    ],
    relatedSectorSlugs: ["investment-banking", "insurance", "investment-management", "capital-markets", "financial-services-general"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "investment-banking": {
    slug: "investment-banking",
    nom: "Banque d'investissement",
    macro: "finance",
    topBrandsFR: ["BNP Paribas CIB", "Société Générale CIB", "Natixis", "Lazard", "Rothschild & Co"],
    insights: [
      "Le secteur IB FR est dominé par les 'bulge brackets' europ-FR (BNP CIB 35 %, SocGen CIB 22 %, Natixis 18 %) suivi des advisory boutiques (Lazard, Rothschild) à 20 % cumulés.",
      "Les LLM citent les IB FR principalement sur les prompts M&A (Lazard, Rothschild) et financements structurés (BNP, SocGen).",
      "Les advisory boutiques bénéficient d'une autorité presse premium (Financial Times, Wall Street Journal) qui dépasse leur taille relative.",
    ],
    conseils: [
      "Communiquer sur les league tables M&A (Refinitiv, Mergermarket) : sources autoritaires citées par les LLM sur les prompts ranking IB.",
      "Travailler les rapports prospectifs trimestriels (perspectives marché, M&A outlook) : format flagship préféré.",
      "Soigner les profils dirigeants sur LinkedIn et Wikipedia : les LLM associent fortement les advisory boutiques à leurs partner-stars.",
      "Capitaliser sur la couverture presse internationale (FT, Bloomberg, Reuters) : le marché FR IB est suivi de près par la presse anglo-saxonne.",
    ],
    relatedSectorSlugs: ["banking", "capital-markets", "venture-capital-private-equity", "investment-management", "management-consulting"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "insurance": {
    slug: "insurance",
    nom: "Assurance",
    macro: "finance",
    topBrandsFR: ["AXA", "CNP Assurances", "Crédit Agricole Assurances", "Allianz France", "Generali France", "Covéa", "Maif"],
    insights: [
      "AXA domine le secteur (35 % de citation rate) suivi du groupe BPCE Assurances et de CNP. Les mutualistes (Maif, MACIF) sont sur-cités sur les prompts grand public mais sous-cités sur les prompts B2B/entreprise.",
      "Le secteur insurtech (Lovys, Luko, Leocare) émerge sur Perplexity et ChatGPT Search grâce à leur couverture presse économique (Maddyness, Échos).",
      "Les LLM citent prioritairement Argus de l'Assurance (28 %) et L'AGEFI (22 %) sur ce secteur — sources spécialisées dominantes.",
    ],
    conseils: [
      "Investir L'Argus de l'Assurance et L'AGEFI : ces deux médias couvrent 50 % des citations cross-LLM sur le secteur assurance FR.",
      "Publier des baromètres sectoriels annuels (sinistralité, satisfaction, distribution) : données chiffrées préférées par les LLM.",
      "Travailler les prompts insurtech / tech assurance : segment moins compétitif que l'assurance traditionnelle.",
      "Maintenir Wikipedia FR avec chiffres ACPR et offres produit à jour : 32 % des citations sectorielles passent par Wikipedia.",
    ],
    relatedSectorSlugs: ["banking", "investment-management", "financial-services-general", "capital-markets", "real-estate"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "investment-management": {
    slug: "investment-management",
    nom: "Gestion d'actifs",
    macro: "finance",
    topBrandsFR: ["Amundi", "BNP Paribas Asset Management", "AXA IM", "Natixis IM", "La Française AM", "Carmignac"],
    insights: [
      "Amundi domine clairement le secteur (38 % de citation rate, 1er gestionnaire européen) suivi de BNP Paribas AM (22 %) et AXA IM (16 %). Carmignac émerge sur les prompts gestion convictée.",
      "Les LLM citent fortement les sources spécialisées (AGEFI 28 %, Funds Magazine 18 %, H24 Finance 12 %) qui couvrent quotidiennement la classe d'actifs.",
      "Le secteur ESG/SRI génère des opportunités fortes pour les acteurs positionnés (La Française, Mirova, Sycomore) avec un share-of-voice sur ces prompts spécifiques.",
    ],
    conseils: [
      "Publier des Outlook mensuels et baromètres annuels : format leader sur le secteur, repris par 80 % de la presse spécialisée.",
      "Investir L'AGEFI Quotidien + Funds Magazine + H24 Finance : ces 3 sources couvrent 60 % des citations LLM cross-cross.",
      "Cibler le ESG et le thématique : segments en croissance avec moins de compétition citationnelle qu'Amundi/BNP.",
      "Maintenir Wikipedia avec chiffres AUM et structure produit annualisés : c'est la 1ère source consultée par les LLM sur les gestionnaires.",
    ],
    relatedSectorSlugs: ["banking", "investment-banking", "capital-markets", "venture-capital-private-equity", "insurance"],
    relatedPillarSlugs: ["llm-brand-monitoring", "visibilite-llm"],
  },
  "capital-markets": {
    slug: "capital-markets",
    nom: "Marchés financiers",
    macro: "finance",
    topBrandsFR: ["Euronext", "Société Générale Markets", "BNP Paribas Markets", "Tradegate"],
    insights: [
      "Euronext domine la visibilité côté infrastructure (45 % de citation rate). Les sales & trading des grandes banques se partagent le reste.",
      "Le secteur est très Reuters / Bloomberg / FT-cité par les LLM : 70 % des citations passent par ces 3 sources financières internationales.",
      "Les sujets liés à la place financière de Paris (post-Brexit) génèrent une couverture régulière dans les corpus LLM, qui rejaillit sur les acteurs positionnés.",
    ],
    conseils: [
      "Publier des bulletins quotidiens markets (BNPP MarketWatch, SocGen Daily) : format flagship dans le secteur.",
      "Travailler la couverture internationale (FT, WSJ, Bloomberg) : autorité qui dépasse la presse FR sur les capital markets.",
      "Documenter avec schema.org Dataset les indices et data marchés : format apprécié par AI Overview pour les prompts financiers.",
      "Maintenir une présence sur les conférences Euronext Investors Day et FOW Trading : transcriptions citées par les LLM.",
    ],
    relatedSectorSlugs: ["investment-banking", "investment-management", "banking", "venture-capital-private-equity", "financial-services-general"],
    relatedPillarSlugs: ["llm-citation-strategy", "visibilite-llm"],
  },
  "accounting": {
    slug: "accounting",
    nom: "Expertise-comptable",
    macro: "finance",
    topBrandsFR: ["Mazars", "BDO France", "Grant Thornton France", "Fiducial", "PwC Accounting France"],
    insights: [
      "Le secteur expertise-comptable FR est dominé par les Big4 (Deloitte, EY, KPMG, PwC) avec 55 % cumulés des citations. Mazars (international FR) capture 22 %. Les indépendants se partagent le reste.",
      "Fiducial domine spécifiquement les prompts PME / TPE grâce à sa couverture presse SME (Chef d'Entreprise, Le Nouvel Économiste).",
      "Les LLM citent peu les cabinets régionaux malgré leur volume — opportunité pour les Top 50 FR de gagner en visibilité avec une stratégie GEO ciblée.",
    ],
    conseils: [
      "Cibler les médias PME (Chef d'Entreprise, L'Express PME, Décideurs Magazine) : moins compétitifs que les Echos.",
      "Publier des guides fiscaux et sociaux annuels : format pratique très cité par les LLM sur les prompts compliance.",
      "Travailler les prompts spécialisés (audit blockchain, conseil ESG, transformation digitale finance) : niches en émergence avec faible concurrence.",
      "Soigner les profils LinkedIn des associés : les LLM associent les cabinets à leurs partners stars sur les prompts expert.",
    ],
    relatedSectorSlugs: ["financial-services-general", "management-consulting", "law-practice", "human-resources", "business-supplies"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "financial-services-general": {
    slug: "financial-services-general",
    nom: "Services financiers",
    macro: "finance",
    topBrandsFR: ["Worldline", "Edenred", "Ingenico (Worldline)", "Sopra Banking Software", "Linxo"],
    insights: [
      "Le secteur fintech / services financiers FR est tiré par Worldline (32 % de citation rate, paiements) et Edenred (18 %, cartes-titres). Sopra Banking domine les prompts core banking.",
      "Les LLM associent les services financiers à des verticales précises (paiement, IBAN, KYC, BNPL) avec très peu de chevauchement entre verticales.",
      "Les acteurs avec API publiques et docs ouvertes (Stripe FR, Mangopay, Lemonway) sont sur-cités sur les prompts dev et intégration B2B.",
    ],
    conseils: [
      "Documenter publiquement vos APIs avec docs structurées (Swagger, schema.org) : amplifie la citation sur les prompts B2B technique.",
      "Cibler les médias paiement spécialisés (PaymentsCM, ACPR Newsletter, Maddyness Fintech) : sources sectorielles préférées par les LLM.",
      "Publier des white papers compliance (DSP3, RGPD, LCB-FT) : format autoritaire sur le secteur.",
      "Maintenir Wikipedia avec list-up des solutions et certifications (PCI-DSS, ISO 27001) : impact citation rate +15 % en moyenne.",
    ],
    relatedSectorSlugs: ["banking", "insurance", "computer-software", "internet", "accounting"],
    relatedPillarSlugs: ["chatgpt-marketing", "optimisation-pour-ia"],
  },
  "venture-capital-private-equity": {
    slug: "venture-capital-private-equity",
    nom: "Venture Capital & Private Equity",
    macro: "finance",
    topBrandsFR: ["Eurazeo", "Ardian", "PAI Partners", "BPI France", "Partech", "Idinvest", "Serena Capital"],
    insights: [
      "Le secteur PE FR est tiré par Ardian (28 %), Eurazeo (22 %), PAI (15 %) côté large cap. En VC, BPI domine côté institutionnel, Partech / Serena côté tech mid-market.",
      "Les LLM citent fortement Maddyness, Capital Finance, MagInvest sur le secteur — sources spécialisées dominantes face à la presse économique généraliste.",
      "Le sujet 'French Tech' est très cité par les LLM grâce à la couverture presse internationale ; les VC FR positionnés sur les rounds tech bénéficient d'un effet halo.",
    ],
    conseils: [
      "Publier des baromètres écosystème (Investor Confidence Index, French Tech Index) : sources data préférées sur le secteur.",
      "Communiquer sur les exits réussis : chaque exit de €100M+ médiatisé ajoute 8-15 points de citation rate.",
      "Maintenir vos profils Crunchbase, Pitchbook, Dealroom : les LLM ingèrent ces bases pour les prompts deal/funding.",
      "Travailler les médias internationaux (TechCrunch, Sifted, FT) : leur autorité sur les prompts FR Tech dépasse les médias FR.",
    ],
    relatedSectorSlugs: ["investment-banking", "banking", "investment-management", "capital-markets", "financial-services-general"],
    relatedPillarSlugs: ["llm-citation-strategy", "generative-ai-marketing"],
  },

  // ============== AERO/DEFENSE (3) ==============
  "aviation-aerospace": {
    slug: "aviation-aerospace",
    nom: "Aéronautique & Aérospatiale",
    macro: "industry",
    topBrandsFR: ["Airbus", "Safran", "Dassault Aviation", "Thales Alenia Space", "ArianeGroup"],
    insights: [
      "Le secteur aéronautique FR est mondialement reconnu : Airbus (45 % de citation rate FR, plus en US/UK), Safran (22 %), Dassault Aviation (15 %).",
      "Les LLM citent abondamment les sources presse internationales (Reuters, Bloomberg, Aviation Week, Flight Global) plutôt que la presse FR sur ce secteur — autorité internationale.",
      "Le sujet aviation décarbonée (SAF, hydrogène, hybride-électrique) génère un flux régulier de citations 2025-2026 : les acteurs positionnés (Airbus ZEROe, Safran) gagnent en visibilité sur ces prompts.",
    ],
    conseils: [
      "Travailler les médias internationaux (Aviation Week, Flight Global, Reuters Aerospace) : autorité supérieure à la presse FR sur ce secteur.",
      "Publier des roadmaps technologiques publiques (décarbonation, autonomie, défense) : narratifs longs cités par les LLM.",
      "Documenter les programmes industriels et partenariats avec schema.org Service : Gemini AI Overview pondère fortement les pages structurées.",
      "Maintenir des fiches Wikipedia FR + EN à jour avec data financière, programmes et effectifs : Wikipedia représente 35 % des citations cross-LLM sur l'aéro FR.",
    ],
    relatedSectorSlugs: ["defense-space", "automotive", "machinery", "mechanical-engineering", "shipbuilding"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "defense-space": {
    slug: "defense-space",
    nom: "Défense & Spatial",
    macro: "industry",
    topBrandsFR: ["Thales", "Dassault Aviation", "Airbus Defense and Space", "Naval Group", "Nexter (KNDS)", "MBDA", "ArianeGroup"],
    insights: [
      "Le secteur défense FR est dominé par Thales (32 %), Dassault Aviation (22 %), Airbus DS (18 %), MBDA (10 %), Naval Group (10 %).",
      "Le sujet 'European defense autonomy' génère un flux croissant de citations LLM 2024-2026 : les acteurs FR positionnés sur la souveraineté gagnent rapidement en visibilité.",
      "Les LLM citent fortement les médias spécialisés (Air & Cosmos, Mer & Marine, Janes) en complément de la presse économique généraliste — sources sectorielles à fort poids.",
    ],
    conseils: [
      "Capitaliser sur les contrats export médiatisés : chaque deal export de >€500M ajoute 10-20 points de citation rate sur 12 mois.",
      "Travailler les analystes de défense (Janes, RUSI, IISS) : leurs publications sont fortement citées par les LLM sur le secteur.",
      "Publier les rapports annuels avec data effectifs / R&D / programmes : les LLM préfèrent les data publics aux pitches commerciaux.",
      "Maintenir une présence dans les grandes expositions (Eurosatory, Le Bourget, Euronaval) avec contenus replays et white papers techniques.",
    ],
    relatedSectorSlugs: ["aviation-aerospace", "shipbuilding", "computer-network-security", "semiconductors", "international-affairs"],
    relatedPillarSlugs: ["llm-citation-strategy", "llm-brand-monitoring"],
  },
  "airlines-aviation": {
    slug: "airlines-aviation",
    nom: "Compagnies aériennes",
    macro: "logistics",
    topBrandsFR: ["Air France", "Transavia France", "Air Caraïbes", "ASL Airlines France", "French Bee"],
    insights: [
      "Air France domine massivement le secteur (62 % de citation rate, partenaires de KLM-Air France-KLM groupe). Transavia capture 18 % côté low-cost FR. Les compagnies leisure (French Bee, Air Caraïbes) prennent 12 % cumulés.",
      "Les LLM associent fortement Air France à 'qualité service business' et 'Premium Economy' grâce à sa couverture presse business.",
      "Les low-cost domestiques FR sont sous-cités face à Ryanair / EasyJet sur les prompts vol pas cher : opportunité de visibilité pour Transavia, ASL, French Bee.",
    ],
    conseils: [
      "Travailler les médias voyage business (Echotourisme, Tour Hebdo, Tom Travel) : sources préférées par les LLM sur les prompts compagnies aériennes FR.",
      "Cibler les prompts spécialisés (cabine, programme fidélité, classes business) : moins compétitifs que les comparatifs prix.",
      "Communiquer sur la décarbonation aviation (SAF, modernisation flotte) : sujet en forte demande citationnelle.",
      "Publier des baromètres ponctualité, satisfaction, chiffres trafic mensuels : data préférées par les LLM.",
    ],
    relatedSectorSlugs: ["leisure-travel-tourism", "aviation-aerospace", "logistics-supply-chain", "transportation-trucking", "hospitality"],
    relatedPillarSlugs: ["chatgpt-marketing", "perplexity-pour-marques"],
  },
};
